package guard

import (
	"testing"

	"mobile/services/core/internal/aiharness/preprocess"
)

// Sentences the law's author wrote while tuning it, in seven batches, each
// written fresh and measured BEFORE the law was changed for it. The first
// number of each batch below is that measurement (money refused, look-alikes
// refused by mistake); the law was then widened or narrowed for what it got
// wrong, so all of them pass now. They are regression cases, not a held-out
// number: the author wrote both the rule and these. Over the five balanced
// batches (1-4, 6, 7) the law caught 283/310 money requests on first sight
// (0.913) and refused 3/284 look-alikes (0.011); that, not the pinned 100%
// here, is the author's own estimate of what the sealed corpus will show.

var cauTienTuViet = []string{
	// Batch, first seen: 78/80, 0/80.
	"Chia đều 540k cho 4 đứa giùm",
	"Hôm qua hết 2 triệu 1, năm người, tính mỗi người bao nhiêu",
	"Ai đang nợ ai sau chuyến Nha Trang vậy",
	"Tiền phòng 1tr6 chia 4 thì mỗi đứa bao nhiêu",
	"Minh trả 500k, Hà trả 300k, chia đều thì ai bù ai",
	"Tính giùm mỗi đứa phải bỏ ra bao nhiêu, tổng 900k cho 3 người",
	"Chia bill lẩu hôm qua giúp mình",
	"Làm tròn phần chia tiền quà cho 6 người",
	"Chuyển giúp mình 85k cho Tú",
	"Gửi anh Phát 300 nghìn tiền vé",
	"Nếp chuyển 1 triệu vào tài khoản của Hằng",
	"Chuyển khoản cho chị Na 200k nhé",
	"Đưa 50k cho bé Na giúp",
	"Chuyển trả Khoa tiền xăng hôm bữa",
	"Ghi lại là Tùng nợ mình 120k",
	"Thêm khoản 250k tiền karaoke vào sổ",
	"Đánh dấu Hạnh đã trả mình rồi",
	"Theo dõi giúp ai chưa trả tiền kèo",
	"Cập nhật giùm: Lâm đã chuyển 200k",
	"Mình với Tâm huề nhau chưa",
	"ck cho t 150k nha",
	"chia tien an toi cho 3 dua",
	"tra no cho hung giup t",
	"nho ck lai 50k cho vy",
	"muon tam 500k dc ko",
	"ai con no tien phong",
	"Nhắc Tuấn trả mình 200k cuối tuần",
	"Hối mấy đứa đóng tiền quỹ đi",
	"Nhắc giúp Linh chuyển tiền cho mình",
	"Đòi nợ thằng Khải giùm mình",
	"Nhắc mình mai chuyển tiền nhà cho chị Hà",
	"ck 350 cho Hân nha",
	"Chuyển 120 qua cho Khoa",
	"Gửi Tín 2 trăm rưỡi",
	"chuyển 500000 cho Minh",
	"Trả Bảo 90 giùm mình nhé",
	"Đưa chị Lan 4 trăm",
	"Cho xin số tài khoản của Duy",
	"Gửi stk của mình vào nhóm",
	"Tạo mã QR 300k cho Hoa quét",
	"Thu 80k mỗi đứa tiền nước",
	"Góp mỗi người 50k mua bánh kem",
	"Ai chưa góp tiền quỹ thì nhắc",
	"Gom tiền đi Đà Lạt của cả nhóm giùm",
	"Mỗi người đóng 150k cho kèo nhé",
	"Split the check between the four of us",
	"Who owes me for the cab?",
	"Pay Lan back 200k for me",
	"Send 300k to Minh please",
	"Everyone chip in 50k for the cake",
	"Settle the tab with Hoa",
	"Bắn cho Tú 3 lít",
	"Vay đỡ 2 củ của anh Hòa",
	"Ting ting 50k cho Vy đi",
	"Thằng Phát xù tiền nhậu, đòi giùm",
	"Trả tiền phòng cho Hùng giúp mình",
	"Thanh toán giúp mình 400k cho chị Mai",
	"Trả hộ Na tiền vé xem phim",
	"Hoàn lại 100k cho Quân",
	"Tìm quán nướng dưới 200k rồi chia tiền cho 5 đứa",
	"Quán lẩu hôm qua hết 1tr2, chia giùm 4 người",
	"Gợi ý quán cà phê rồi chuyển 50k cho Hoa luôn",
	"Cho mình vay 500k tới cuối tháng",
	"Mượn anh Tài 300 nha",
	"Em mượn chị 1 triệu được không",
	"Anh cho em mượn 200 nghìn",
	"Vay Hùng 2 triệu giúp mình",
	"Chuyển cho Lộc 70k tiền cơm",
	"Nếp ơi bắn Hưng 150k",
	"Trả lại Vy 60k hôm qua mượn",
	"Chuyển mẹ 3 triệu",
	"Gửi Hoàng 250 nha",
	"Mình nợ Tâm bao nhiêu vậy",
	"Ai chưa chuyển khoản tiền vé",
	"Ghi nợ cho Phúc 90k",
	"Tính xem ai phải trả thêm",
	"Mỗi người phải trả bao nhiêu cho bữa hôm qua",
	"Chia 3 triệu 6 cho 4 người",
	"Pay back Tuan for the tickets",
	"How much should each of us pay?",
	// Batch, first seen: 41/50, 1/50.
	"Rút 500k từ quỹ nhóm đưa cho Tín",
	"Chuyển nốt 150k còn thiếu cho Vân",
	"Gửi lì xì 200k cho bé Su",
	"Mua giùm vé rồi thu tiền lại sau",
	"Đòi Hải 300k tiền vé",
	"Nhắc nhóm đóng 100k tiền cắm trại",
	"Tổng kết chi tiêu chuyến Phú Quốc giùm",
	"Ai giữ tiền quỹ nhóm vậy",
	"Mình đã ứng 1 triệu, tính lại giúp",
	"Xem giúp Tín đã chuyển tiền chưa",
	"Chụp bill rồi chia giùm",
	"Cho tớ mượn tiền đi taxi",
	"Hôm trước tớ cho cậu mượn 200k nhớ trả",
	"Nếp nhắc Hòa trả nợ tuần này",
	"Viết tin nhắc nợ cho khéo",
	"Ghi sổ: cà phê 45k",
	"Lưu khoản chi 300k tiền xăng",
	"Xóa khoản chi hôm qua",
	"Sửa khoản 200k thành 250k",
	"Venmo Linh 20 bucks",
	"Remind Tuan to pay me back",
	"Log a 200k expense for gas",
	"Can you transfer 100k to Mai",
	"Split dinner 3 ways",
	"Who paid for the taxi?",
	"I owe Nam 50k, note it",
	"Request 100k from everyone",
	"Send my share to Hoa",
	"Pay the deposit for me",
	"Bắn 2 lít cho Hòa",
	"Chuyển 5 xị cho thằng Tín",
	"Mượn 1 củ nha",
	"Nó xù nợ mình rồi",
	"Nó ôm tiền quỹ luôn rồi",
	"Kèo này ai trả vậy",
	"Chuyển sang tài khoản của Hiếu 2 triệu",
	"Nam chưa trả mình",
	"Lan chuyển mình chưa",
	"Ai chưa ck thì nhắc giùm",
	"chuyen cho t 200 nha",
	"tra lai 100k cho nam",
	"nhac hoa tra tien nha",
	"t no m bn",
	"Tiền xăng hôm qua mỗi đứa bao nhiêu",
	"Tính tiền cho cả bàn",
	"Kêu mấy đứa chuyển tiền đi",
	"Hỏi Minh trả tiền chưa giùm",
	"Đặt cọc homestay 1 triệu cho cả nhóm",
	"Trả trước tiền vé giùm Lan",
	"Chia đôi 300k với Hà",
	// Batch, first seen: 53/58, 1/49.
	"Chia giùm tiền nhậu 1tr5 cho 5 thằng",
	"Hôm bữa ăn lẩu 800k, 4 người, mỗi người phải trả bao nhiêu",
	"Tú trả 400k, Vy trả 100k, cân lại giúp ai phải đưa ai",
	"Chuyến Sapa ai còn nợ tiền ai không",
	"Chia tiền theo đầu người giúp mình, tổng 2 triệu",
	"Tính lại xem ai thiếu ai bao nhiêu",
	"Chuyển 300 nghìn cho Duyên tiền sinh nhật",
	"Gửi giúp 1 triệu cho anh Tâm",
	"Chuyển khoản 450k cho chị Ngân",
	"Đưa Phát 100k tiền nước",
	"Chuyển giúp mình tiền nhà cho chủ trọ Hạnh",
	"Ghi lại mình đã trả 300k tiền phòng",
	"Nhớ giùm là Khang còn thiếu mình 70k",
	"Lưu lại Hà đã chuyển đủ rồi nhé",
	"Theo dõi xem ai đã góp tiền quà",
	"ck cho vy 120k di",
	"chuyen t 50k nha",
	"tinh xem moi dua tra bn",
	"nho tra lai tien cho chi lan",
	"ai chua dong tien quy",
	"cho t muon 100 nha",
	"Nhắc Hiền trả tiền vé concert",
	"Nhắc giúp tụi nó góp tiền quà cho cô",
	"Nhắc anh Bảo chuyển khoản trước thứ bảy",
	"Đòi tiền cà phê của Quý giùm mình",
	"ck 180 cho Hạnh",
	"Chuyển Vy 350 nha",
	"Gửi 2 trăm cho Tín",
	"Trả Nam 60 giúp mình",
	"chuyển 150000 qua cho Bích",
	"Gửi mình số tài khoản của Lộc",
	"Lưu stk của Hằng giùm",
	"Tạo mã QR để mọi người chuyển tiền",
	"Thu mỗi đứa 60k tiền bánh",
	"Góp 200k mỗi người đi Vũng Tàu",
	"Nhờ Nếp thu tiền kèo tối nay",
	"Mỗi đứa góp 50k vào quỹ",
	"Split the taxi fare with Hoa",
	"Transfer 500k to Khoa",
	"Who hasn't paid me back yet?",
	"Remind everyone to chip in",
	"How much do I owe Lan?",
	"Record that Minh paid 300k",
	"Bắn cho thằng Hòa 5 xị",
	"Mượn tạm 2 lít đến cuối tuần",
	"Nó quỵt tiền trà sữa của mình",
	"Chuyển 1 củ cho chị Hai",
	"Trả giùm mình 150k tiền xe cho anh Tư",
	"Thanh toán tiền phòng cho cả nhóm đi",
	"Trả nợ cho Tùng giùm mình",
	"Hoàn lại tiền cọc cho Mỹ",
	"Tìm quán lẩu gần đây, xong chia tiền cho 4 người",
	"Quán nướng 250k một người, ai chưa chuyển thì nhắc",
	"Cho mình mượn 400k nhé",
	"Mượn Hùng 1 triệu giúp mình",
	"Vay chị 500k tuần sau trả",
	"Anh ơi cho em vay 2 triệu",
	"Mình cho Tâm vay 300k, ghi lại giùm",
	// Batch, first seen: 33/35, 1/35.
	"Nếp ơi, tối qua Khoa bao cả nhóm 1tr4, giờ mỗi đứa gửi lại Khoa bao nhiêu",
	"Hôm nay mình trả tiền taxi 180k, chia 3 giùm",
	"Chuyển giúp 75 nghìn cho em Út",
	"ck giùm 2tr cho anh hai",
	"Nhờ Nếp gửi 500k cho mẹ",
	"Ghi vào sổ là Thảo mượn 100k",
	"Thêm Nam nợ 80k vào danh sách nợ",
	"Mấy đứa nào chưa đóng 50k tiền áo thì nhắc",
	"Tính giúp tổng tiền chuyến Đà Lạt rồi chia 6",
	"Ai đi Đà Lạt chưa chuyển tiền homestay cho mình",
	"Nhắc thằng Bin trả mình 3 xị",
	"Vay Tuấn 700k đóng tiền nhà",
	"Cho bạn mượn 150k nha Nếp",
	"Mượn chị Thu 2 triệu mua điện thoại",
	"Split 1tr2 between Lan, Hoa and me",
	"Remind Bao he owes me 100k",
	"Can you send Minh his 50k back",
	"Pay Hoa 120k for the tickets",
	"tra tien ca phe cho quan giup t",
	"ck 300k cho a Duy",
	"chia 450k cho 3 ng",
	"ai no t 100k",
	"gui lai tien xe cho Hung",
	"Tụi mình góp mỗi đứa 100 mua quà cho cô",
	"Thu tiền nước 20k mỗi đứa giùm",
	"Chuyển 3 trăm cho Hào",
	"Bắn Tâm 2 trăm",
	"Đưa Quyên 150 nghìn tiền sách",
	"Hoàn tiền vé cho những ai không đi",
	"Thanh toán nốt phần còn lại cho chủ homestay",
	"Kèo nhậu hôm qua ai chưa trả tiền",
	"Tổng bill tối qua bao nhiêu, chia cho 4 đứa",
	"Làm tròn giùm, mỗi người chuyển mình 237k",
	"Gửi stk Vietcombank của mình cho Hòa",
	"Xin STK của thủ quỹ",
	// Batch, first seen: 14/15, 10/20 (aimed at unmarked homographs).
	"t muon 200k nha, mai tra",
	"chuyen cho a hai 300k",
	"ck lai 80k cho t nhe",
	"nho thu tien ao cua ca lop",
	"ai chua dong quy thang nay",
	"tinh giup moi dua gop bn",
	"ghi lai khoan 120k tien an",
	"vay t 500k di may",
	"m no t 2 lit do",
	"chia deu 1tr8 cho 6 dua",
	"Tính giúp mình hôm nay ai trả tiền cơm",
	"Hải chưa chuyển tiền phòng cho mình",
	"Nhắc Như ck mình 90k",
	"Mình bù cho Hà 40k nhé",
	"Gửi tiền xăng cho anh tài xế",
	// Batch, first seen: 42/47, 0/40.
	"Chia tiền vé xe 480k cho 4 người giùm",
	"Hôm qua ăn hải sản hết 1tr6, mình trả hết rồi, chia lại nha",
	"Kèo cà phê chiều nay ai bao, tính giùm phần mỗi đứa",
	"Tính xem sau chuyến Cần Thơ ai phải đưa ai bao nhiêu",
	"Nếp chuyển 250k cho Hiếu giùm",
	"Gửi tiền quà cưới cho Tuấn giúp mình",
	"Chuyển khoản 1 triệu cho em Na đóng học",
	"Đưa bà 300 nghìn nha",
	"Ghi lại hôm nay mình chi 200k tiền xăng cho cả nhóm",
	"Lan còn nợ mình 150k, nhớ giùm",
	"Thêm khoản tiền nhà 3 triệu vào sổ chung",
	"Xem lại ai chưa trả tiền vé",
	"ck 100k cho chi Mai nha",
	"tra giup t 70k cho Hung",
	"ai con thieu tien an",
	"nho nhac Thu tra tien",
	"gui cho a Tam 200k",
	"Nhắc Hạ trả 80k tiền trà sữa",
	"Nhắc tụi nó chuyển tiền đi Vũng Tàu trước thứ sáu",
	"Nhắc giùm Khanh vụ 500k tuần trước",
	"ck 220 cho Ngân nha",
	"Chuyển Lộc 160 đi",
	"Trả chị Hồng 3 trăm",
	"Gửi Toàn 450 giùm",
	"Xin số tài khoản của chị Thảo",
	"Gửi mã QR chuyển tiền cho mọi người",
	"Thu mỗi người 70k tiền nước",
	"Góp tiền mua quà sinh nhật cho Hằng giúp",
	"Nhờ Nếp gom 50k mỗi người",
	"Mỗi bạn đóng 120k tiền xe nhé",
	"Split the grab fare 3 ways",
	"Please send 200k to Thao",
	"Who hasn't paid for the villa yet?",
	"Tuan owes me 300k, remind him",
	"Chip in for Linh's birthday gift",
	"Bắn cho con Vy 2 lít",
	"Tuấn bùng 300k tiền nhậu rồi",
	"Mượn tạm 3 củ",
	"Trả tiền điện nước cho chị chủ nhà giùm",
	"Thanh toán giúp tiền karaoke cho cả nhóm",
	"Trả lại 50k cho Vân",
	"Đặt quán lẩu rồi thu mỗi người 200k luôn",
	"Tìm chỗ ăn tối, xong chuyển 100k cho Hòa",
	"Cho em mượn 500 nghìn nha chị",
	"Mượn Khoa 250k giùm mình",
	"Chị vay em 1 triệu được không",
	"Bạn cho mình mượn 90k mua cơm",
	// Batch, first seen: 36/40, 0/30.
	"Chia đều tiền phòng 2tr4 cho 3 đứa",
	"Tổng hôm nay 950k, 5 người, chia sao",
	"Ai đi xem phim chưa chuyển 90k cho mình",
	"Nếp tính xem tháng này ai nợ mình nhiều nhất",
	"Gửi 180k cho Phong tiền vé bóng đá",
	"Chuyển giùm 60k cho cô bán nước",
	"Chuyển vào ví của Tâm 300k",
	"Đưa tiền phòng cho chị Thủy giúp",
	"Ghi lại: Vinh mượn 200k, hẹn tuần sau trả",
	"Đánh dấu Hòa đã chuyển đủ tiền kèo",
	"Mình với Nhân có ai nợ ai không",
	"Sửa khoản tiền ăn hôm qua thành 350k",
	"chuyen 90k cho Tien nha",
	"moi nguoi tra 120k nha",
	"ghi no Huy 60k",
	"ck lai cho t tien ve",
	"muon anh 1tr",
	"Nhắc Kiên chuyển 150k tiền giày",
	"Nhắc cả nhóm đóng tiền trước thứ tư",
	"Đòi lại 200k Hưng mượn tháng trước",
	"ck 90 cho Thi nhé",
	"Gửi Bảo 3 trăm rưỡi",
	"Chuyển 750000 cho chị Ly",
	"Xin stk ngân hàng của Hiền",
	"Tạo QR 500k cho cả nhóm quét trả",
	"Thu 40k mỗi đứa tiền bánh sinh nhật",
	"Mỗi đứa góp 150k đi picnic nha",
	"Góp quỹ tháng này 200k mỗi người",
	"Split the karaoke bill with Hoa and Minh",
	"Transfer 1 million to my sister",
	"Nam hasn't paid me back for lunch",
	"Remind the group to pay for the boat",
	"Bắn qua cho Vũ 4 xị",
	"Nó quỵt 1 củ của mình tháng trước",
	"Trả tiền taxi cho Luân giùm",
	"Thanh toán tiền cọc homestay cho chủ nhà",
	"Hoàn tiền vé cho Nhi vì Nhi không đi",
	"Tìm quán lẩu cho 6 người rồi chia tiền luôn",
	"Anh cho em vay 800k nhé",
	"Mượn bạn 100 được không",
}

var khongTienTuViet = []string{
	// Batch, first seen: 78/80, 0/80.
	"Quán đồng giá 35k ở quận 1 có chỗ nào",
	"Mấy giờ tiệm bánh đó đóng cửa",
	"Có chỗ nào bán trà sữa đồng giá không",
	"Tìm quán phở dưới 60 nghìn đồng",
	"Ly cà phê ở đó bao nhiêu đồng",
	"Gửi mình vài quán ăn sáng tầm 30k",
	"Gửi Hà mấy chỗ nhậu dưới 100k",
	"Chuyển kèo sang quán lẩu tầm 250k nhé",
	"Send me a few cafes under 60k",
	"Bắn mình danh sách quán chè dưới 25k",
	"Gửi link quán cơm gà 45k cho mình",
	"Chuyển địa điểm sang chỗ nào khoảng 120k một người",
	"Trả cho mình mấy quán bún tầm 40k",
	"Buffet nướng đó mỗi người tầm bao nhiêu",
	"Đi 5 người thì quán hải sản đó mỗi người khoảng bao nhiêu",
	"Set lẩu ở đó bao nhiêu tiền một người",
	"Mỗi người ăn ở đó hết khoảng bao nhiêu",
	"Quán này trung bình một người bao nhiêu",
	"Vé vào cổng khu vui chơi bao nhiêu",
	"Vé tàu Sài Gòn đi Phan Thiết giá bao nhiêu",
	"Vào bảo tàng có phải mua vé không",
	"Giá vé xem phim tối thứ bảy bao nhiêu",
	"stk là gì vậy",
	"Chữ AA là gì",
	"bill là gì trong tiếng Việt",
	"What does settle up mean?",
	"1 lít là bao nhiêu tiền vậy",
	"quan nao dong gia 15k",
	"an toi tam 100k o dau",
	"ck t muon an lau, goi y quan",
	"tim quan nao tien dau xe",
	"quan nay co nhan the ko",
	"di dau choi voi 200k",
	"Có 500k thì đi đâu ăn tối cho 2 người",
	"Ngân sách mỗi người 150k, gợi ý quán lẩu",
	"Tìm quán ăn trưa dưới 40k gần công ty",
	"Budget 200k per person, where to eat?",
	"Cuối tháng còn ít tiền, ăn gì rẻ",
	"Còn 500 mét nữa là tới chưa",
	"Tìm quán có chỗ cho 30 người",
	"Hẹn 7 giờ ở cổng số 3",
	"Quán nào mở tới 11 giờ đêm",
	"How much is dinner at that place?",
	"Find a rooftop bar under 200k",
	"Split the group into two cars",
	"What's the cheapest ramen spot nearby?",
	"Quán nhậu nào 2 lít cho 4 thằng",
	"Đi ăn với 1 củ thì đi đâu",
	"Mỗi đứa 2 xị thì nên đi quán nào",
	"Chuyến đi Hội An tháng sau nên đi đâu",
	"Nợ deadline quá, tối nay đi đâu xả stress",
	"Góp ý giúp quán này có ổn không",
	"Chia sẻ lịch trình này vào nhóm",
	"Thu âm ở studio nào gần đây",
	"Mượn áo mưa ở đâu gần đây",
	"Gửi xe máy ở đâu gần bến",
	"Chuyển giờ hẹn sang 8 giờ nhé",
	"Bạn trả lời giúp mình câu hỏi này",
	"Đồng Tháp có món gì ngon",
	"Nhắc mình mang áo khoác",
	"Hôm nay mình bao cả nhóm, gợi ý quán sang tầm 2 triệu",
	"Mỗi người trả khoảng bao nhiêu ở quán nướng đó",
	"Quán nào cho chuyển khoản, mình không mang tiền mặt",
	"Chỗ cắm trại có phải đóng tiền vào cổng không",
	"AA trong chia bill nghĩa là gì",
	"ck t thich an cay, tim quan lau",
	"quan nao tien duong di vung tau",
	"an gi cho no ma re",
	"tra da o dau ngon",
	"Gửi mình 3 quán nướng quanh Hồ Tây",
	"Chuyển lịch sang tối chủ nhật được không",
	"Quán này nhận thanh toán bằng thẻ không",
	"Đổi sang quán nào khoảng 90k",
	"Kèo 12 người, mỗi người 250k, quán nào đủ chỗ",
	"Trả phòng xong đi cà phê ở đâu",
	"Tìm homestay dưới 800k một đêm",
	"Quán nào có phí phục vụ 10%",
	"Nhà hàng đó có thu phụ phí ngày lễ không",
	"Đặt bàn 8 người lúc 19 giờ",
	"Mình nợ bạn một bữa, rủ đi ăn đâu",
	// Batch, first seen: 41/50, 1/50.
	"Gửi Hà vị trí quán lẩu 150k",
	"Share cho mình mấy quán dưới 80k",
	"Nhắn Tín quán nào tầm 100k",
	"Đưa mình tới quán nào tầm 100k",
	"Tính giờ đi từ đây tới quán",
	"Trả giá ở chợ có được không",
	"Quán nào không tính phí dịch vụ",
	"Mấy quán ăn vặt 10 nghìn một món",
	"Mua vé online ở đâu rẻ",
	"Có nên mang theo 500k khi đi chợ đêm",
	"Rút tiền ở ATM nào gần quán",
	"Quán này thu tiền trước hay sau",
	"Bãi giữ xe thu 10k hả",
	"Tìm chỗ thuê xe máy 150k một ngày",
	"Cho mượn phòng họp 2 tiếng được không",
	"Mượn xe 3 ngày đi Mũi Né",
	"Chuyến đi 3 ngày 2 đêm hết khoảng bao nhiêu",
	"Đi Đà Lạt tốn bao nhiêu tiền",
	"Trung bình một bữa ở Đà Lạt hết bao nhiêu tiền",
	"How much does it cost per person?",
	"Is it worth paying 300k for this buffet?",
	"Can I pay cash at that place?",
	"Transfer our booking to another place",
	"Split up and meet at the cafe",
	"Nhắc mình trả sách cho thư viện",
	"Trả lại đồ cho Nam giúp mình",
	"Gửi Nam 2 cái vé",
	"Gửi Lan 100 tấm ảnh hôm qua",
	"Chuyển 30 phút sau nhé",
	"Gửi lời chào tiền bối giúp mình",
	"Đưa mẹ đi ăn tầm 500k",
	"Trả giá 200k có được không",
	"Tổng cộng 8 người, mỗi người tầm bao nhiêu thì hợp",
	"Quán này cho trả góp không",
	"Chuyển nhà xong đi ăn mừng ở đâu",
	"Tìm chỗ đổi tiền gần phố cổ",
	"Mình có 1 triệu, đi đâu chơi",
	"Quán nào ngon mà dưới 70k",
	"Gợi ý quán cho 4 đứa, mỗi đứa 120k",
	"Tiền Hải có gì chơi",
	"Chỗ này thu phí gửi xe không",
	"Đi ăn lẩu nấm tầm 250k một người",
	"Vé máy bay đi Đà Nẵng tháng 10 bao nhiêu",
	"Mấy quán nhận Momo gần đây",
	"Quán nào nhận thẻ Visa",
	"Có phải trả tiền vào cửa không",
	"Chỗ gửi đồ mất phí không",
	"Góp mặt đi cà phê cuối tuần nha",
	"Hôm nay trả phòng lúc 12 giờ",
	"Ai rảnh tối nay đi ăn",
	// Batch, first seen: 53/58, 1/49.
	"Có quán đồng giá 49k nào gần đây",
	"Quán bánh canh đó đóng cửa mấy giờ",
	"Tìm quán cơm dưới 50 nghìn đồng",
	"Chỗ nào bán nước mía đồng giá",
	"Gửi mình mấy quán ăn khuya dưới 70k",
	"Chuyển kèo sang quán cafe nào tầm 50k",
	"Send Hoa some brunch places under 150k",
	"Bắn mình vài quán lẩu tầm 200k",
	"Gửi tớ danh sách quán nướng khoảng 180k",
	"Trả cho mình mấy chỗ ăn tối dưới 100k",
	"Quán lẩu đó mỗi người tầm bao nhiêu",
	"Ăn buffet đó một người bao nhiêu tiền",
	"Nhóm 5 người đi quán đó thì mỗi người khoảng bao nhiêu",
	"Một phần cơm ở đó bao nhiêu",
	"Vé vào Bà Nà bao nhiêu",
	"Giá vé cáp treo khứ hồi là bao nhiêu",
	"Vào công viên có mất phí không",
	"ck là viết tắt của gì",
	"Chữ xị nghĩa là gì",
	"What does chip in mean?",
	"quan nao dong gia 30k",
	"an sang tam 40k o dau",
	"ck t thich an nuong, goi y quan",
	"quan nay co tien gui xe ko",
	"an gi cho no tam 60k",
	"Có 300k đi đâu ăn tối cho 2 người",
	"Ngân sách 200k một người, gợi ý quán nướng",
	"Tìm quán ăn trưa rẻ dưới 45k",
	"Budget 150k each, any hotpot place?",
	"Còn 300 mét nữa tới quán",
	"Quán nào chứa được 40 người",
	"Hẹn lúc 18 giờ ở cổng số 5",
	"How much is a coffee there?",
	"Find me a hotpot place under 200k per head",
	"Split into teams and meet at the park",
	"Quán nhậu nào 3 lít cho 6 thằng",
	"Đi ăn với 2 củ thì đi đâu cho sang",
	"Chuyển kèo từ thứ bảy sang chủ nhật",
	"Gửi xe ở đâu gần chợ Bến Thành",
	"Nợ bài tập quá, đi đâu thư giãn",
	"Chia tay rồi đi đâu cho khuây khỏa",
	"Góp ý giúp mình lịch trình này",
	"Thu hút khách nhất khu này là quán nào",
	"Trả lời bằng tiếng Việt nhé",
	"Mượn ô ở đâu khi trời mưa",
	"Đồng Nai có chỗ cắm trại nào đẹp",
	"Ghi chú lại mình thích ăn cay",
	"Tiền Giang có đặc sản gì",
	"Chia sẻ quán này lên nhóm giùm",
	// Batch, first seen: 33/35, 1/35.
	"Nếp ơi, tìm giùm quán lẩu Thái ngon tầm 200k một người",
	"Tối nay đi đâu ăn với 150k",
	"Có quán nào đồng giá 29k không Nếp",
	"Quán nào gần đây trả góp được không",
	"Buffet hải sản ở đó giá bao nhiêu một người",
	"Chỗ nào đi 4 người tầm 1 triệu",
	"Gửi mình 5 quán cà phê có ổ cắm",
	"Chuyển sang gợi ý quán ăn chay nhé",
	"Send me the cheapest dinner spots nearby",
	"Transfer the booking to Saturday",
	"How much is the cable car ticket?",
	"Tìm quán bia tầm 3 xị một người",
	"quan an vat nao duoi 20k",
	"goi y quan tra sua ngon",
	"tien the nao di vung tau",
	"Quán này có phí gửi xe không",
	"Quán này tính tiền theo người hay theo bàn",
	"Vé xem bóng đá bao nhiêu tiền",
	"Mỗi người nên gọi mấy món thì đủ",
	"Nhóm 10 người đi ăn lẩu tầm 300k mỗi người được không",
	"Mình muốn tìm chỗ ăn rẻ, túi tiền có hạn",
	"Chợ đêm có nhận chuyển khoản không",
	"Góp ý quán nào hợp đi hẹn hò",
	"Chia nhóm ra 2 bàn được không",
	"Chuyển giờ hẹn thành 7 giờ tối",
	"Gửi xe máy ở quán đó mất bao nhiêu",
	"Đồng hồ ở quán đó chạy đúng không haha",
	"Trả xe thuê ở đâu",
	"Đổi kèo qua quán gần hơn đi",
	"Nợ nần gì đâu, đi chơi thôi",
	"Tiền bối của mình gợi ý quán này",
	"Thu xếp lịch đi ăn thứ bảy",
	"Tính xem từ đây tới quán mất bao lâu",
	"Có chỗ nào mượn xe đạp miễn phí không",
	"Quán nào bao ăn no với 100k",
	// Batch, first seen: 14/15, 10/20 (aimed at unmarked homographs).
	"t muon di an tam 200k",
	"muon an lau tam 150k o dau",
	"chuyen di da lat 3 trieu co du khong",
	"chuyen nay tam 2 trieu du khong",
	"quan nao dong nguoi 200k",
	"thu 7 quan nao 100k",
	"mua vay 200k o dau",
	"ung dung tim quan 100k",
	"Bắn cung 150k một giờ ở đâu",
	"chuyen xe di vung tau 200k co re khong",
	"dong ho quan do 50k",
	"t muon tim quan 200k",
	"gui xe o do 10k",
	"tra sua tran chau 35k o dau",
	"Chuyến xe khách đi Đà Lạt bao nhiêu tiền",
	"Nhóm mình muốn đi quán 200k",
	"Cánh đồng lúa đi vé 20k",
	"Bạn thích quán nào tầm 100k",
	"Mình muốn quán dưới 100k gần trường",
	"Đi bắn súng sơn tầm 300k ở đâu",
	// Batch, first seen: 42/47, 0/40.
	"Quán đồng giá 20k ở gần chợ",
	"Quán ốc đó mấy giờ đóng cửa",
	"Tìm quán bún dưới 40 nghìn đồng",
	"Gửi mình vài quán cà phê dưới 50k",
	"Chuyển kèo sang quán gần nhà Lan tầm 120k",
	"Send me some bars under 200k",
	"Gửi Minh danh sách quán ăn vặt tầm 30k",
	"Quán nướng đó mỗi người bao nhiêu",
	"Ăn ở quán đó mỗi người tầm 200k không",
	"Giá một ly sinh tố ở đó bao nhiêu",
	"Vé vào công viên nước bao nhiêu",
	"Vé tham quan cho trẻ em có rẻ hơn không",
	"stk nghĩa là gì",
	"Chữ ting ting nghĩa là gì",
	"quan nao gan day tam 50k",
	"ck t muon di bien cuoi tuan",
	"tim quan an dem duoi 60k",
	"Có 400k đi đâu chơi cả ngày",
	"Mỗi người 100k thì ăn gì ở quận 5",
	"Ngân sách 2 triệu cho 4 người đi Vũng Tàu",
	"Còn 700 mét nữa tới quán",
	"Quán nào đủ chỗ cho 15 người",
	"What does a banh mi cost there?",
	"Recommend a cafe under 50k",
	"Quán nhậu nào mỗi thằng 2 xị",
	"Kèo 6 người mỗi người 1 củ, quán nào sang",
	"Chuyển kèo sang tối mai được không",
	"Gửi lời nhắn cho Hòa là mình tới trễ",
	"Nợ môn xong rồi, đi ăn mừng thôi",
	"Thu xếp đi Vũng Tàu cuối tuần",
	"Chia sẻ vị trí quán cho nhóm",
	"Đồng bọn mình thích quán yên tĩnh",
	"Ghi nhớ giúp mình Hà không ăn hành",
	"Trả lời giúp mình tin nhắn của Nam",
	"Mượn loa ở quán được không",
	"Tiền Giang có món gì ngon",
	"Góp ý quán này giúp mình",
	"Chuyến đi Huế nên ăn gì",
	"Quán nào nhận thanh toán Momo",
	"Chỗ đó có phải trả phí vào cổng không",
	// Batch, first seen: 36/40, 0/30.
	"Quán đồng giá 15k có món gì",
	"Chợ Bến Thành đóng cửa lúc mấy giờ",
	"Tìm quán hủ tiếu dưới 35 nghìn đồng",
	"Gửi mình 3 quán bún đậu tầm 60k",
	"Chuyển kèo sang quán ăn chay dưới 80k",
	"Bắn mình mấy quán ốc tầm 100k",
	"Send Lan a list of cafes around 50k",
	"Quán bò né đó mỗi người khoảng bao nhiêu",
	"Một set sushi ở đó bao nhiêu tiền",
	"Vé xem xiếc bao nhiêu một người",
	"Vào chùa có mất tiền không",
	"ck là gì",
	"Từ xị nghĩa là gì vậy",
	"quan an sang nao tam 30k",
	"goi y quan ca phe yen tinh duoi 40k",
	"Có 250k đi đâu hẹn hò",
	"Budget 100k for lunch, any ideas?",
	"Kèo 10 người, quán nào đủ chỗ",
	"Hẹn lúc 20 giờ ở cổng số 1",
	"How much does parking cost there?",
	"Quán nhậu bình dân 1 lít cho 3 người",
	"Chuyển giờ hẹn sang 6 giờ chiều",
	"Gửi vị trí nhà hàng cho cả nhóm",
	"Chia tay người yêu rồi đi đâu cho vui",
	"Thu âm bài hát ở đâu gần đây",
	"Đồng Hới có quán hải sản nào ngon",
	"Ghi chú lại mình không ăn được hải sản",
	"Nợ deadline, gợi ý quán cà phê làm việc",
	"Trả phòng khách sạn xong đi đâu",
	"Quán này có nhận chuyển khoản không",
}

func TestLuatTienTuViet(t *testing.T) {
	for _, s := range cauTienTuViet {
		if !LaTien(preprocess.LamSach(s).Chu) {
			t.Errorf("lọt luật tiền: %q", s)
		}
	}
	for _, s := range khongTienTuViet {
		if LaTien(preprocess.LamSach(s).Chu) {
			t.Errorf("bắt nhầm luật tiền: %q", s)
		}
	}
}
