#!/usr/bin/env python3
"""Does the window gate actually guard, and is it stronger than the one it replaced?

Run from the repo root:

    python3 scripts/mutation_cong_cua_so_model.py

The claim under test is narrow and worth stating exactly. After #297 landed,
`create_app` builds eight guards in front of the shared model key: seven
`FixedWindowLimiter` windows and one `CachedReasonWriter` cache for `GET
/places`, which has no actor to key a window on. The property that has to hold
is that no two doors resolve to the *same object* -- sharing one is the cheap
way to "add" a limiter, and it makes one feature's burst disable its neighbour.

The gate that claimed to enforce this hand-listed seven attribute names and
asserted the count of distinct ids was seven. That is a tautology over its own
list: a door whose name is absent cannot fail it. This script measures both
shapes against the same mutations, so the difference is a number rather than an
argument.

Reading the table: a mutation that BREAKS the property must be RED, and the
control that PRESERVES it must be GREEN. An all-red table proves nothing -- it
cannot tell "this gate guards the property" from "this gate dislikes edits".
"""

from __future__ import annotations

import dataclasses
import pathlib
import subprocess
import sys
import textwrap

REPO = pathlib.Path(__file__).resolve().parents[1]
API = REPO / "services" / "api"
MAIN = API / "app" / "api" / "main.py"
LIMITS = API / "app" / "api" / "search_rate_limit.py"
GATE = API / "tests" / "api" / "test_contextual_suggestion_rate_limit.py"

# The gate as it stood before this branch rewrote it, reconstructed verbatim so
# the comparison is against what actually shipped and not a strawman of it.
LEGACY_GATE = '''\
"""The gate as it stood before the rewrite, kept only so the table can measure it.

Generated by `scripts/mutation_cong_cua_so_model.py`. Not part of the suite.
"""

from app.api.main import create_app


def test_every_route_that_reaches_the_model_carries_its_own_window():
    state = create_app().state
    windows = {
        id(state.search_limiter),
        id(state.receipt_scan_limiter),
        id(state.chat_expense_limiter),
        id(state.screenshot_scan_limiter),
        id(state.companion_turn_limiter),
        id(state.suggestion_limiter),
        id(state.contextual_suggestion_limiter),
    }

    assert len(windows) == 7
'''

LEGACY_PATH = API / "tests" / "api" / "test_legacy_window_shape_generated.py"

# The two cases in the new gate that carry the property. Named explicitly so a
# mutation that reddens some unrelated case in the file cannot be misread as
# this gate biting -- "đỏ ở file khác không phải đã gác".
NEW_TARGET = (
    "tests/api/test_contextual_suggestion_rate_limit.py"
    "::test_every_door_onto_the_model_carries_its_own_guard "
    "tests/api/test_contextual_suggestion_rate_limit.py"
    "::test_the_roster_of_doors_onto_the_model_is_accounted_for"
)
LEGACY_TARGET = "tests/api/test_legacy_window_shape_generated.py"


@dataclasses.dataclass
class Mutation:
    name: str
    why: str
    path: pathlib.Path
    old: str
    new: str
    breaks_property: bool


MUTATIONS = [
    Mutation(
        name="M1 cửa thứ chín dùng chung cửa sổ với cửa thứ nhất",
        why=(
            "A door added after the gate was written, aliased onto an existing "
            "window. This is the shape the legacy gate was blind to by "
            "construction, and the reason this branch had to change it."
        ),
        path=MAIN,
        old="    application.state.contextual_suggestion_limiter = (\n"
        "        build_contextual_suggestion_limiter()\n"
        "    )\n",
        new="    application.state.contextual_suggestion_limiter = (\n"
        "        build_contextual_suggestion_limiter()\n"
        "    )\n"
        "    application.state.ninth_limiter = application.state.search_limiter\n",
        breaks_property=True,
    ),
    Mutation(
        name="M2 cửa thứ tám dùng chung cửa sổ với cửa thứ sáu",
        why=(
            "The one shape the legacy gate did cover: an aliased limiter whose "
            "name it already knew. Kept so the table shows what was already "
            "guarded and is not read as the rewrite inventing all the coverage."
        ),
        path=MAIN,
        old="    application.state.contextual_suggestion_limiter = (\n"
        "        build_contextual_suggestion_limiter()\n"
        "    )\n",
        new="    application.state.contextual_suggestion_limiter = (\n"
        "        application.state.suggestion_limiter\n"
        "    )\n",
        breaks_property=True,
    ),
    Mutation(
        name="M3 gỡ hẳn cửa thứ bảy của #297",
        why=(
            "Deleting `GET /places`'s cache leaves that door onto the model key "
            "with nothing in front of it. The legacy gate never named "
            "`reason_writer`, so it cannot notice."
        ),
        path=MAIN,
        old="    application.state.reason_writer = CachedReasonWriter()\n",
        new="",
        breaks_property=True,
    ),
    Mutation(
        name="M4 phá cơ chế khám phá (kiểu guard rỗng)",
        why=(
            "Anti-vacuity. If discovery silently finds nothing, 'no two doors "
            "share a guard' is trivially true of an empty roster and the gate "
            "goes green while measuring nothing -- 0/0 read as a pass."
        ),
        path=GATE,
        old="_MODEL_GUARD_TYPES = (FixedWindowLimiter, CachedReasonWriter)",
        new="_MODEL_GUARD_TYPES = ()",
        breaks_property=True,
    ),
    Mutation(
        name="M5 ĐỐI CHỨNG: đổi hằng số trần, giữ nguyên tính chất",
        why=(
            "The ceiling is not the property. Each door still owns its own "
            "object, so this row must stay GREEN -- it is what separates a gate "
            "that guards the invariant from one that merely dislikes diffs."
        ),
        path=LIMITS,
        old="CONTEXTUAL_SUGGESTION_LIMIT_PER_WINDOW = RECEIPT_SCAN_LIMIT_PER_WINDOW",
        new="CONTEXTUAL_SUGGESTION_LIMIT_PER_WINDOW = 99",
        breaks_property=False,
    ),
]


def run(target: str) -> bool:
    """True when the target is green."""

    done = subprocess.run(
        [sys.executable, "-m", "pytest", *target.split(), "-q", "--no-header"],
        cwd=API,
        capture_output=True,
        text=True,
    )
    return done.returncode == 0


def apply(mutation: Mutation) -> None:
    text = mutation.path.read_text()
    if mutation.old not in text:
        raise SystemExit(
            f"anchor not found for {mutation.name} in {mutation.path}.\n"
            "Read the file and fix the anchor -- a mutation that fails to "
            "apply prints nothing and reads exactly like a gate that held."
        )
    if text.count(mutation.old) != 1:
        raise SystemExit(
            f"anchor for {mutation.name} matches {text.count(mutation.old)} "
            "places; it must match exactly one or the patch may land on a copy."
        )
    mutation.path.write_text(text.replace(mutation.old, mutation.new, 1))


def restore() -> None:
    subprocess.run(
        ["git", "checkout", "--", str(MAIN), str(LIMITS), str(GATE)],
        cwd=REPO,
        check=True,
    )


def main() -> int:
    dirty = subprocess.run(
        ["git", "status", "--porcelain", str(MAIN), str(LIMITS), str(GATE)],
        cwd=REPO,
        capture_output=True,
        text=True,
    ).stdout.strip()
    if dirty:
        raise SystemExit(
            "uncommitted changes in a file this script mutates:\n"
            f"{dirty}\n"
            "It restores by `git checkout --`, which would delete them. Commit "
            "first."
        )

    LEGACY_PATH.write_text(LEGACY_GATE)
    try:
        print("Bản sạch — cả hai cổng phải XANH trước khi bảng dưới có nghĩa")
        base_new = run(NEW_TARGET)
        base_legacy = run(LEGACY_TARGET)
        print(f"  cổng mới: {'XANH' if base_new else 'ĐỎ'}")
        print(f"  cổng cũ : {'XANH' if base_legacy else 'ĐỎ'}")
        if not (base_new and base_legacy):
            raise SystemExit("baseline không xanh — dừng, bảng sẽ vô nghĩa")

        rows = []
        for mutation in MUTATIONS:
            apply(mutation)
            try:
                new_green = run(NEW_TARGET)
                legacy_green = run(LEGACY_TARGET)
            finally:
                restore()
            rows.append((mutation, new_green, legacy_green))
            print(f"\n{mutation.name}")
            print(
                textwrap.fill(
                    mutation.why, 78, initial_indent="  ", subsequent_indent="  "
                )
            )
            print(
                f"  cổng mới: {'XANH' if new_green else 'ĐỎ'}"
                f"   cổng cũ: {'XANH' if legacy_green else 'ĐỎ'}"
            )

        print("\n" + "=" * 78)
        failures = []
        caught_new = caught_legacy = breakers = 0
        for mutation, new_green, legacy_green in rows:
            if mutation.breaks_property:
                breakers += 1
                caught_new += not new_green
                caught_legacy += not legacy_green
                if new_green:
                    failures.append(f"{mutation.name}: cổng MỚI không bắt được")
            elif not new_green:
                failures.append(f"{mutation.name}: đối chứng phải XANH mà lại ĐỎ")

        print(f"đột biến phá tính chất: {breakers}")
        print(f"  cổng mới bắt được: {caught_new}/{breakers}")
        print(f"  cổng cũ  bắt được: {caught_legacy}/{breakers}")
        for failure in failures:
            print(f"THIẾU SÓT: {failure}")
        return 1 if failures else 0
    finally:
        LEGACY_PATH.unlink(missing_ok=True)


if __name__ == "__main__":
    raise SystemExit(main())
