//go:build postgres

package repo

// The call sequences of the seven W9 routes (routes/sessions.py and
// routes/auth.py), written against the Go repository, for the `route.*` steps
// of auth_repo_oracle_postgres_test.go. The Python side of such a step runs
// the real ApiService method behind one request; this side runs the repository
// calls that method makes, in its order, with the service's decisions (the
// permission table, the OTP domain's two plans, the identity derivations) in
// the fewest lines that decide the same branch. This is test code, not the
// service port: it exists so the oracle proves, statement by statement, that
// the Go repository called in this order is what the Python route does.
//
// Two routes carry their authentication here rather than taking an actor for
// granted, because for this wave authentication IS the subject: `GET /sessions`
// and `DELETE /sessions/{id}` resolve the bearer through
// actor_for_session_token first, exactly as the `get_actor` dependency does.
// `DELETE /sessions/current` deliberately does not -- that route declares no
// actor, and a dead bearer still answers 204.
//
// One request holds one SQLAlchemy identity map, but nothing here memoises a
// read against it, and that is a measured fact rather than a simplification.
// SQLAlchemy's identity map holds WEAK references, and every method of this
// repository turns the ORM row into a frozen dataclass and drops the row on the
// way out; under CPython the object is collected the moment the method returns,
// so the next `session.get` of the same id issues its SELECT again. The oracle
// shows it: `DELETE /sessions/current` reads the row by digest and then reads
// it again by primary key, and `DELETE /sessions/{id}` reads it twice more.

import (
	"crypto/hmac"
	"encoding/hex"
	"errors"
	"strings"
	"time"

	"mobile/services/core/internal/domain/blocking"
	"mobile/services/core/internal/domain/permissions"
	"mobile/services/core/internal/identity"
)

// authKey is MOBILE_PERSON_ID_KEY for this run: generated by the test and
// handed to the Python container, never written down.
var authKey []byte

// The OTP domain's DEFAULT_LIMITS (app/domain/otp.py).
const (
	otpCodeTTLSeconds        = 300
	otpMaxAttempts           = 5
	otpResendCooldownSeconds = 60
	otpMaxPerWindow          = 5
	otpWindowSeconds         = 900
)

// accountSessionTTL is service.ACCOUNT_SESSION_TTL.
const accountSessionTTL = 30 * 24 * time.Hour

type authRoute struct {
	repo Repository
	now  time.Time
	a    map[string]any

	// ids is the `uuid.uuid4()` queue the case pinned for the service.
	ids []string
}

func newAuthRoute(repo Repository, a map[string]any) *authRoute {
	p := &authRoute{repo: repo, now: argInstant(argString(a, "now")), a: a}
	if ids, ok := a["ids"].([]any); ok {
		for _, id := range ids {
			p.ids = append(p.ids, id.(string))
		}
	}
	return p
}

func (p *authRoute) text(key string) string { return argString(p.a, key) }

func (p *authRoute) nextID() string {
	if len(p.ids) == 0 {
		panic("the case ran out of pinned uuid4 values")
	}
	id := p.ids[0]
	p.ids = p.ids[1:]
	return id
}

// require is `_require_permission(action, actor, facts)` with the actor's real
// roles -- the ones actor_grants just read, not a constant.
func (p *authRoute) require(action string, roles []string, proven []string) error {
	f, err := permissions.NewAuthorizationFacts(p.text("actor_id"), roles, nil, proven, "api_service")
	if err != nil {
		return err
	}
	if _, allowed, err := permissions.DenialReason(action, f); err != nil {
		return err
	} else if !allowed {
		return refuse(403, "permission_denied")
	}
	return nil
}

// --- the bearer, and who the server answers as ------------------------------

type authActor struct {
	id    string
	roles []string
}

var authInvalidSession = refuse(401, "authentication_required")

// actorForSessionToken is ApiService.actor_for_session_token: every refusal is
// the same 401. The deadline is `expires_at <= now`, so a session expiring at
// exactly this instant is already gone.
func (p *authRoute) actorForSessionToken(token string) (*authActor, error) {
	record, err := p.repo.GetAccountSessionByDigest(bg, digestOf(token))
	if err != nil {
		return nil, err
	}
	at := pythonInstant(p.now)
	if record == nil || record.RevokedAt != nil || !record.ExpiresAt.After(at) {
		return nil, authInvalidSession
	}
	grants, err := p.actorGrants(record.PersonID)
	if err != nil {
		return nil, err
	}
	if !grants.PersonExists {
		return nil, authInvalidSession
	}
	return &authActor{id: record.PersonID, roles: grants.Roles}, nil
}

func (p *authRoute) actorGrants(personID string) (ActorGrants, error) {
	return p.repo.ActorGrants(bg, personID)
}

// --- the answer every door builds -------------------------------------------

// sessionResponse is `_session_response`: the holder's name and the groups
// they may go to, computed once so a client told who it is is told where it
// may go in the same answer.
func (p *authRoute) sessionResponse(personID string) error {
	if _, err := p.repo.GetPerson(bg, personID); err != nil {
		return err
	}
	return p.contextSummaries(personID)
}

// contextSummaries is `_context_summaries`: the roster read, then two more
// reads per pair -- the other person, then the edge between them.
func (p *authRoute) contextSummaries(personID string) error {
	rows, err := p.repo.ListPersonContextSummaries(bg, personID)
	if err != nil {
		return err
	}
	for _, row := range rows {
		if row.Kind != "pair" || row.CounterpartID == nil {
			continue
		}
		other, err := p.repo.GetPerson(bg, *row.CounterpartID)
		if err != nil {
			return err
		}
		edge, err := p.repo.GetFriendEdge(bg, personID, *row.CounterpartID)
		if err != nil {
			return err
		}
		var domainEdge *blocking.Edge
		if edge != nil {
			domainEdge = &blocking.Edge{State: edge.State, DecidedByID: edge.DecidedByID}
		}
		_ = blocking.DMAllowed(domainEdge, other == nil || other.DeletedAt != nil)
	}
	return nil
}

// --- POST /sessions ---------------------------------------------------------

func (p *authRoute) createSession() error {
	token := p.text("token")
	digest := digestOf(token)
	invite, err := p.repo.GetOutingInviteByDigest(bg, digest)
	if err != nil {
		return err
	}
	if invite == nil || invite.InvitedPersonID == nil {
		return refuse(404, "invite_not_found")
	}
	at := pythonInstant(p.now)
	if invite.RevokedAt != nil || !invite.ExpiresAt.After(at) {
		return refuse(404, "invite_not_found")
	}
	outing, err := p.repo.GetOuting(bg, invite.OutingID)
	if err != nil {
		return err
	}
	if outing == nil {
		return refuse(404, "invite_not_found")
	}
	personID := *invite.InvitedPersonID
	if _, err := p.repo.ConsumeNamedInviteSecret(bg, invite.ID, digest, personID, p.now); err != nil {
		var conflict *Conflict
		if errors.As(err, &conflict) {
			return refuse(404, "invite_not_found")
		}
		return err
	}
	if _, err := p.repo.EnsureInvitedMembership(bg, outing.ContextID, personID, invite.InvitedByID,
		"named", p.now); err != nil {
		return err
	}
	inviteID := invite.ID
	if _, err := p.repo.CreateAccountSession(bg, AccountSessionInput{PersonID: personID,
		TokenDigest: digestOf(p.text("session_token")), IssuedFromInviteID: &inviteID,
		ExpiresAt: p.now.Add(accountSessionTTL), Now: p.now, IssuedVia: "invite"}); err != nil {
		return err
	}
	return p.sessionResponse(personID)
}

// --- GET /sessions, DELETE /sessions/current, DELETE /sessions/{id} ---------

func (p *authRoute) listSessions() error {
	bearer := p.text("bearer")
	actor, err := p.actorForSessionToken(bearer)
	if err != nil {
		return err
	}
	if err := p.require("manage_own_sessions", actor.roles, []string{"is_self"}); err != nil {
		return err
	}
	if _, err := p.repo.ListAccountSessions(bg, actor.id, p.now); err != nil {
		return err
	}
	_, err = p.repo.GetAccountSessionByDigest(bg, digestOf(bearer))
	return err
}

func (p *authRoute) revokeCurrentSession() error {
	record, err := p.repo.GetAccountSessionByDigest(bg, digestOf(p.text("bearer")))
	if err != nil || record == nil {
		return err
	}
	_, err = p.repo.RevokeAccountSession(bg, record.ID, p.now)
	return err
}

func (p *authRoute) revokeSession() error {
	actor, err := p.actorForSessionToken(p.text("bearer"))
	if err != nil {
		return err
	}
	if err := p.require("manage_own_sessions", actor.roles, []string{"is_self"}); err != nil {
		return err
	}
	record, err := p.repo.GetAccountSession(bg, p.text("session_id"))
	if err != nil {
		return err
	}
	if record == nil || record.PersonID != actor.id {
		return refuse(404, "session_not_found")
	}
	_, err = p.repo.RevokeAccountSession(bg, record.ID, p.now)
	return err
}

// --- POST /auth/otp/request -------------------------------------------------

func (p *authRoute) otpPhone() (string, []byte, error) {
	canonical, ok := identity.CanonicalMobile(p.text("phone"))
	if !ok {
		return "", nil, refuse(422, "phone_not_mobile")
	}
	digest, err := identity.DerivePhoneDigest(canonical, authKey)
	if err != nil {
		return "", nil, err
	}
	return canonical, digest, nil
}

func (p *authRoute) requestOtp() error {
	_, digest, err := p.otpPhone()
	if err != nil {
		return err
	}
	since := p.now.Add(-otpWindowSeconds * time.Second)
	recent, err := p.repo.RecentOtpChallenges(bg, digest, since)
	if err != nil {
		return err
	}
	if problem := planOtpRequest(recent, p.now); problem != nil {
		return problem
	}
	challengeID := p.nextID()
	code := p.text("code")
	codeDigest, err := identity.DeriveCodeDigest(uuidArray16(challengeID), code, authKey)
	if err != nil {
		return err
	}
	if _, err := p.repo.CreateOtpChallenge(bg, OtpChallengeInput{ChallengeID: challengeID,
		PhoneDigest: digest, CodeDigest: codeDigest,
		ExpiresAt: p.now.Add(otpCodeTTLSeconds * time.Second), Now: p.now}); err != nil {
		return err
	}
	if fails, _ := p.a["sms_fails"].(bool); fails {
		// attempts is already 0, so the only column that moves is consumed_at:
		// a code the gateway never delivered must not be spendable.
		if _, err := p.repo.RecordOtpAttempt(bg, challengeID, 0, true, p.now); err != nil {
			return err
		}
		return refuse(503, "sms_unavailable")
	}
	return nil
}

// planOtpRequest is app.domain.otp.plan_request as the route reads it: a
// cooldown since the newest challenge, then a ceiling per window.
func planOtpRequest(recent []OtpChallenge, now time.Time) error {
	windowStart := now.Add(-otpWindowSeconds * time.Second)
	var inWindow []OtpChallenge
	for _, row := range recent {
		if row.CreatedAt.After(windowStart) {
			inWindow = append(inWindow, row)
		}
	}
	if len(inWindow) == 0 {
		return nil
	}
	latest := inWindow[0].CreatedAt
	for _, row := range inWindow {
		if row.CreatedAt.After(latest) {
			latest = row.CreatedAt
		}
	}
	cooldownLeft := otpResendCooldownSeconds - now.Sub(latest).Seconds()
	if cooldownLeft > 0 {
		return refuse(429, "otp_resend_too_soon")
	}
	if len(inWindow) >= otpMaxPerWindow {
		return refuse(429, "otp_too_many_requests")
	}
	return nil
}

// --- POST /auth/otp/verify --------------------------------------------------

// otpVerdict is plan_verify's outcome plus the attempt count to persist.
type otpVerdict struct {
	outcome  string
	attempts int64
}

func planOtpVerify(challenge *OtpChallenge, now time.Time, matches bool) otpVerdict {
	if challenge == nil {
		return otpVerdict{"not_found", 0}
	}
	attempts := challenge.Attempts
	if challenge.ConsumedAt != nil {
		return otpVerdict{"consumed", attempts}
	}
	if !challenge.ExpiresAt.After(now) {
		return otpVerdict{"expired", attempts}
	}
	if attempts >= otpMaxAttempts {
		return otpVerdict{"burned_already", attempts}
	}
	attempts++
	if matches {
		return otpVerdict{"ok", attempts}
	}
	if attempts >= otpMaxAttempts {
		return otpVerdict{"burned", attempts}
	}
	return otpVerdict{"wrong_code", attempts}
}

func (p *authRoute) verifyOtp() error {
	canonical, digest, err := p.otpPhone()
	if err != nil {
		return err
	}
	code := strings.TrimSpace(p.text("code"))
	if code == "" {
		return refuse(422, "code_required")
	}
	at := pythonInstant(p.now)
	challenge, err := p.repo.GetOtpChallenge(bg, p.text("challenge_id"))
	if err != nil {
		return err
	}
	if challenge != nil && !hmac.Equal(challenge.PhoneDigest, digest) {
		challenge = nil
	}
	matches := false
	if challenge != nil {
		want, err := identity.DeriveCodeDigest(uuidArray16(challenge.ID), code, authKey)
		if err != nil {
			return err
		}
		matches = hmac.Equal(challenge.CodeDigest, want)
	}
	verdict := planOtpVerify(challenge, at, matches)
	switch verdict.outcome {
	case "not_found", "consumed", "expired", "burned_already":
		return refuse(404, "otp_challenge_not_found")
	}
	consumed := verdict.outcome == "ok" || verdict.outcome == "burned"
	if _, err := p.repo.RecordOtpAttempt(bg, challenge.ID, verdict.attempts, consumed, p.now); err != nil {
		return err
	}
	if verdict.outcome == "burned" {
		return refuse(429, "otp_too_many_attempts")
	}
	if verdict.outcome == "wrong_code" {
		return refuse(422, "otp_code_invalid")
	}

	subject := hex.EncodeToString(digest)
	bound, err := p.repo.GetAccountIdentity(bg, "phone", subject)
	if err != nil {
		return err
	}
	var personID string
	if bound != nil {
		personID = bound.PersonID
	} else {
		if personID, err = identity.DerivePersonID(canonical, authKey); err != nil {
			return err
		}
		person, err := p.repo.GetPerson(bg, personID)
		if err != nil {
			return err
		}
		if person != nil && person.DeletedAt != nil {
			// Reviving the anonymised row would hand the next holder of this
			// number somebody else's groups and ledger.
			personID, person = p.nextID(), nil
		}
		if person == nil {
			if _, err := p.repo.CreatePerson(bg, personID, authNewPersonName); err != nil {
				// Two verifies raced on a brand-new number; the row exists.
				var conflict *Conflict
				if !errors.As(err, &conflict) {
					return err
				}
			}
		}
	}
	if _, err := p.repo.UpsertAccountIdentity(bg, personID, "phone", subject, p.now); err != nil {
		return err
	}
	if _, err := p.repo.CreateAccountSession(bg, AccountSessionInput{PersonID: personID,
		TokenDigest: digestOf(p.text("session_token")), ExpiresAt: p.now.Add(accountSessionTTL),
		Now: p.now, IssuedVia: "otp"}); err != nil {
		return err
	}
	return p.sessionResponse(personID)
}

// authNewPersonName is ApiService.NEW_PERSON_NAME.
const authNewPersonName = "Thành viên mới"

// authPlaceholderIDToken is what stands in for a Google ID token a case did not
// write down. The verifier behind this route is a stub the case configures, so
// the string itself decides nothing; render_w9_repo_oracle.py defaults to the
// same one.
const authPlaceholderIDToken = "id-token-mau"

// --- POST /auth/google ------------------------------------------------------

func (p *authRoute) loginGoogle() error {
	// Order is the whole of the security argument: a host with no client ids
	// refuses before it reads the token, a blank token is a 422, and a token
	// the verifier does not vouch for is one 401 whatever the reason. None of
	// the three issues a statement.
	if configured, ok := p.a["google_configured"].(bool); ok && !configured {
		return refuse(503, "google_not_configured")
	}
	// A case that does not care about the token carries none, and both sides
	// then stand in the same placeholder: what this route is being measured on
	// is the statements after the token, not the token.
	idToken := p.text("id_token")
	if idToken == "" {
		idToken = authPlaceholderIDToken
	}
	if strings.TrimSpace(idToken) == "" {
		return refuse(422, "id_token_required")
	}
	if invalid, _ := p.a["google_invalid"].(bool); invalid {
		return refuse(401, "google_token_invalid")
	}
	subject := p.text("subject")
	existing, err := p.repo.GetAccountIdentity(bg, "google", subject)
	if err != nil {
		return err
	}
	var personID string
	if existing == nil {
		personID = p.nextID()
		name := authNewPersonName
		if display := p.text("display_name"); display != "" {
			name = display
		}
		if _, refused := p.repo.CreatePersonWithIdentity(bg, personID, name, "google", subject,
			p.now); refused != nil {
			var conflict *Conflict
			if !errors.As(refused, &conflict) {
				return refused
			}
			// Two first logins raced on one `sub`: read the winner back and
			// sign in as that person, or let the conflict stand.
			won, err := p.repo.GetAccountIdentity(bg, "google", subject)
			if err != nil {
				return err
			}
			if won == nil {
				return refused
			}
			personID = won.PersonID
		}
	} else {
		personID = existing.PersonID
		if _, err := p.repo.UpsertAccountIdentity(bg, personID, "google", subject, p.now); err != nil {
			return err
		}
	}
	if _, err := p.repo.CreateAccountSession(bg, AccountSessionInput{PersonID: personID,
		TokenDigest: digestOf(p.text("session_token")), ExpiresAt: p.now.Add(accountSessionTTL),
		Now: p.now, IssuedVia: "google"}); err != nil {
		return err
	}
	return p.sessionResponse(personID)
}

// authRouteGo runs one `route.*` step. The answer is not compared; the
// statements, the probes and the refusal are.
func authRouteGo(repo Repository, name string, a map[string]any) (any, error) {
	p := newAuthRoute(repo, a)
	var err error
	switch name {
	case "route.create_session":
		err = p.createSession()
	case "route.actor_for_session_token":
		_, err = p.actorForSessionToken(p.text("bearer"))
	case "route.list_sessions":
		err = p.listSessions()
	case "route.revoke_current_session":
		err = p.revokeCurrentSession()
	case "route.revoke_session":
		err = p.revokeSession()
	case "route.request_otp":
		err = p.requestOtp()
	case "route.verify_otp":
		err = p.verifyOtp()
	case "route.login_google":
		err = p.loginGoogle()
	default:
		panic("unknown route " + name)
	}
	return nil, err
}
