//go:build postgres

package repo

// Differential test of the W7 repository methods (a trip's plan, its arrivals
// and its invitations) against the real SqlAlchemyApiRepository, driven
// through scripts/render_w7_repo_oracle.py. Same design as
// pair_repo_oracle_postgres_test.go, whose case format, value tags, statement
// normalisation, conflict tagging, row lock probe and comparison it reuses.
//
// What this wave has to pin that the earlier ones did not: two of the methods
// are a SQLAlchemy unit of work rather than a statement, so what is compared
// is not only which rows moved but the order the flush moved them in -- the
// parking pass that keeps uq_outing_stops_position satisfied while a plan is
// permuted, the parent table going first, and the SET list of each UPDATE
// carrying exactly the columns whose value changed.
//
// Invitations are the second sharp edge. The server stores a digest, never a
// token, so the fixture writes sha256 of a short sample word computed inside
// PostgreSQL and every case hands both sides that same word. The Python
// driver also pins secrets.token_urlsafe for a route step, so the digest the
// two sides write is the digest of one token and the table dump can compare
// it byte for byte.
//
// TestOutingRowLocksSerialiseRequests is Go only: the races the Python
// branches name (two arrivals at one stop, two saves of one plan, two
// redemptions of one link).
//
// Without CORE_PYTHON_IMAGE both tests skip; scripts/go_postgres_tier.sh sets
// it and refuses skips.

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	osexec "os/exec"
	"path/filepath"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"mobile/services/core/internal/testdb"
)

// outingContent sorts a row a method generated by what it says rather than by
// the uuid4 it was given: two rows of one step differ in their columns, and
// ordering on the id alone would order them by a random number, which the two
// sides draw independently.
const outingContent = "(to_jsonb(t) - 'id')::text"

var (
	outingsDump      = orderedDump("outings t", fixtureFirst("t.id")+", t.context_id, t.starts_on, "+outingContent+", t.id")
	outingStopsDump  = orderedDump("outing_stops t", fixtureFirst("t.id")+", t.outing_id, t.position, "+outingContent+", t.id")
	outingArrivalDmp = orderedDump("outing_stop_checkins t",
		fixtureFirst("t.id")+", t.stop_id, t.created_at, t.person_id, "+outingContent+", t.id")
	outingInvitesDump = orderedDump("outing_invites t",
		fixtureFirst("t.id")+", t.outing_id, t.created_at, "+outingContent+", t.id")
	outingMembersDump = orderedDump("memberships t",
		fixtureFirst("t.id")+", t.context_id, t.person_id, "+outingContent+", t.id")
)

// probeOutingRowLocks lists the row locks held on every table a W7 method
// locks FOR UPDATE, updates, deletes or references through a foreign key it
// writes, each row named by its key.
var probeOutingRowLocks = func() string {
	var parts []string
	for _, t := range []struct{ table, key string }{
		{"people", "t.id::text"}, {"contexts", "t.id::text"}, {"memberships", "t.id::text"},
		{"outings", "t.id::text"}, {"outing_stops", "t.id::text"}, {"outing_stop_checkins", "t.id::text"},
		{"outing_invites", "t.id::text"}, {"places", "t.id"},
	} {
		parts = append(parts, `SELECT '`+t.table+`' AS rel, `+t.key+` AS id, array_to_string(r.modes, ',') AS modes
			FROM public.pgrowlocks('`+t.table+`') r LEFT JOIN `+t.table+` t ON t.ctid = r.locked_row`)
	}
	return `SELECT l.rel || ' ' || coalesce(l.id, '(superseded row)') || ' ' || l.modes FROM (` +
		strings.Join(parts, " UNION ALL ") + `) l ORDER BY 1`
}()

// ---------------------------------------------------------------------------
// Tags and the Go side
// ---------------------------------------------------------------------------

func tOutingStopRecord(s OutingStop) any {
	return tRecord("OutingStopRecord", "id", tUUID(s.ID), "position", tInt(s.Position),
		"minute_of_day", tInt(s.MinuteOfDay), "label", tStr(s.Label), "place_name", optional(s.PlaceName, tStr),
		"place_id", optional(s.PlaceID, tStr), "day", optional(s.Day, tDay),
		"duration_minutes", optional(s.DurationMinutes, tInt), "time_locked", tBool(s.TimeLocked),
		"meeting_lat", optional(s.MeetingLat, tFloat), "meeting_lng", optional(s.MeetingLng, tFloat),
		"meeting_label", optional(s.MeetingLabel, tStr))
}

func tStopCheckin(c StopCheckin) any {
	return tRecord("StopCheckinRecord", "id", tUUID(c.ID), "stop_id", tUUID(c.StopID),
		"person_id", tUUID(c.PersonID), "created_at", tInstant(c.CreatedAt))
}

func tOutingInvite(i OutingInvite) any {
	return tRecord("OutingInviteRecord", "id", tUUID(i.ID), "outing_id", tUUID(i.OutingID),
		"source", tStr(i.Source), "invited_person_id", optional(i.InvitedPersonID, tUUID),
		"invited_by_id", tUUID(i.InvitedByID), "accepted_at", optional(i.AcceptedAt, tInstant),
		"accepted_by_id", optional(i.AcceptedByID, tUUID), "created_at", tInstant(i.CreatedAt),
		"expires_at", tInstant(i.ExpiresAt), "revoked_at", optional(i.RevokedAt, tInstant))
}

func nilOuting(o *Outing) any {
	if o == nil {
		return nil
	}
	return tOuting(*o)
}

func nilInvite(i *OutingInvite) any {
	if i == nil {
		return nil
	}
	return tOutingInvite(*i)
}

func argTimelineStops(v any) []TimelineStop {
	out := []TimelineStop{}
	for _, item := range v.([]any) {
		stop := item.(map[string]any)
		out = append(out, TimelineStop{MinuteOfDay: argNumber(stop["minute_of_day"]),
			Label: stop["label"].(string), PlaceName: argText(stop["place_name"]),
			PlaceID: argText(stop["place_id"])})
	}
	return out
}

func argItineraryStops(v any) []ItineraryStop {
	out := []ItineraryStop{}
	for _, item := range v.([]any) {
		stop := item.(map[string]any)
		next := ItineraryStop{ID: stop["id"].(string), MinuteOfDay: argNumber(stop["minute_of_day"]),
			Label: stop["label"].(string), PlaceName: argText(stop["place_name"]),
			PlaceID: argText(stop["place_id"]), Day: optionalDay(argText(stop["day"])),
			DurationMinutes: optionalNumber(stop["duration_minutes"]), TimeLocked: true}
		if locked, ok := stop["time_locked"].(bool); ok {
			next.TimeLocked = locked
		}
		if point, ok := stop["meeting_point"].(map[string]any); ok {
			lat, lng := argFloat(point["lat"]), argFloat(point["lng"])
			label := point["label"].(string)
			next.MeetingLat, next.MeetingLng, next.MeetingLabel = &lat, &lng, &label
		}
		out = append(out, next)
	}
	return out
}

// argRawDays reads itinerary_days, which a case writes as JSON text so that
// the key order Python's dicts carry survives the trip through Go.
func argRawDays(v any) []json.RawMessage {
	out := []json.RawMessage{}
	for _, item := range v.([]any) {
		out = append(out, json.RawMessage(item.(string)))
	}
	return out
}

func argExpected(v any) *int64 {
	if v == nil {
		return nil
	}
	n := argNumber(v)
	return &n
}

func outingRepoGoCall(repo Repository, method string, a map[string]any) (any, error) {
	s := func(key string) string { return argString(a, key) }
	now := func() time.Time { return argInstant(s("now")) }
	if strings.HasPrefix(method, "route.") {
		return outingRouteGo(repo, method, a)
	}
	switch method {
	case "get_outing":
		o, err := repo.GetOuting(bg, s("outing_id"))
		return nilOuting(o), err
	case "list_outings":
		rows, err := repo.ListOutings(bg, s("context_id"))
		items := []any{}
		for _, row := range rows {
			items = append(items, tOuting(row))
		}
		return tSeq(items), err
	case "get_outing_stop":
		stop, outing, err := repo.GetOutingStop(bg, s("stop_id"))
		if err != nil || stop == nil {
			return nil, err
		}
		return tSeq([]any{tOutingStopRecord(*stop), tOuting(*outing)}), nil
	case "list_outing_checkins":
		rows, err := repo.ListOutingCheckins(bg, s("outing_id"))
		items := []any{}
		for _, row := range rows {
			items = append(items, tStopCheckin(row))
		}
		return tSeq(items), err
	case "create_stop_checkin":
		c, err := repo.CreateStopCheckin(bg, s("stop_id"), s("person_id"), now())
		return tStopCheckin(c), err
	case "replace_outing_stops":
		o, err := repo.ReplaceOutingStops(bg, s("outing_id"), argTimelineStops(a["stops"]),
			argExpected(a["expected_revision"]))
		return tOuting(o), err
	case "replace_outing_itinerary":
		o, err := repo.ReplaceOutingItinerary(bg, s("outing_id"), argItineraryStops(a["stops"]),
			argRawDays(a["itinerary_days"]), argNumber(a["expected_revision"]))
		return tOuting(o), err
	case "create_outing_invite":
		i, err := repo.CreateOutingInvite(bg, OutingInviteInput{OutingID: s("outing_id"), Source: s("source"),
			InvitedPersonID: argText(a["invited_person_id"]), InvitedByID: s("invited_by_id"),
			TokenDigest: digestOf(s("token")), ExpiresAt: argInstant(s("expires_at")), Now: now()})
		return tOutingInvite(i), err
	case "find_outing_invite_for_person":
		i, err := repo.FindOutingInviteForPerson(bg, s("outing_id"), s("person_id"))
		return nilInvite(i), err
	case "get_outing_invite":
		i, err := repo.GetOutingInvite(bg, s("invite_id"))
		return nilInvite(i), err
	case "get_outing_invite_by_digest":
		i, err := repo.GetOutingInviteByDigest(bg, digestOf(s("token")))
		return nilInvite(i), err
	case "accept_outing_invite":
		i, err := repo.AcceptOutingInvite(bg, s("invite_id"), s("accepted_by_id"), now())
		return tOutingInvite(i), err
	case "revoke_outing_invite":
		i, err := repo.RevokeOutingInvite(bg, s("invite_id"), now())
		return tOutingInvite(i), err
	case "rotate_outing_invite_digest":
		i, err := repo.RotateOutingInviteDigest(bg, s("invite_id"), digestOf(s("token")),
			argInstant(s("expires_at")), now())
		return tOutingInvite(i), err
	case "ensure_invited_membership":
		m, err := repo.EnsureInvitedMembership(bg, s("context_id"), s("person_id"), s("invited_by_id"),
			s("origin"), now())
		return tMembership(m), err
	}
	return photoGoCall(repo, method, a)
}

func runOutingGoCase(t *testing.T, pool *pgxpool.Pool, c oracleCase) []any {
	t.Helper()
	tx, err := pool.Begin(bg)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = tx.Rollback(bg) }()
	for _, sql := range c.Setup {
		if _, err := tx.Exec(bg, sql); err != nil {
			t.Fatalf("setup: %v\n%s", err, sql)
		}
	}
	steps := []any{}
	for _, step := range c.Steps {
		for _, sql := range step.Before {
			if _, err := tx.Exec(bg, sql); err != nil {
				t.Fatalf("before: %v\n%s", err, sql)
			}
		}
		rec := &recorder{Querier: tx}
		value, err := outingRepoGoCall(Repository{Q: rec}, step.Call, step.Args)
		statements := []any{}
		for _, sql := range rec.log {
			statements = append(statements, normalizeSQL(sql))
		}
		out := map[string]any{"result": nil, "error": nil, "warnings": []any{}, "statements": statements,
			"probes": nil}
		if err != nil {
			out["error"] = pairRepoGoError(err)
			steps = append(steps, generic(t, out))
			break
		}
		out["result"] = value
		probes := []any{}
		for _, sql := range step.Probes {
			rows, err := tx.Query(bg, sql)
			if err != nil {
				t.Fatalf("probe: %v\n%s", err, sql)
			}
			texts, err := pgx.CollectRows(rows, pgx.RowTo[string])
			if err != nil {
				t.Fatal(err)
			}
			probes = append(probes, append([]string{}, texts...))
		}
		out["probes"] = probes
		steps = append(steps, generic(t, out))
	}
	return steps
}

// normalizeOutingSteps is normalizePairSteps for probeOutingRowLocks.
func normalizeOutingSteps(steps []any, c oracleCase) []any {
	spec, _ := json.Marshal(c)
	known := map[string]bool{}
	for _, id := range uuidText.FindAllString(string(spec), -1) {
		known[id] = true
	}
	out := make([]any, len(steps))
	for i, step := range steps {
		out[i] = step
		probes, _ := step.(map[string]any)["probes"].([]any)
		for j, probe := range c.Steps[i].Probes {
			if j >= len(probes) {
				continue
			}
			rows, ok := probes[j].([]any)
			if !ok {
				continue
			}
			switch probe {
			case probeOutingRowLocks:
				masked := make([]string, len(rows))
				for k, row := range rows {
					masked[k] = uuidText.ReplaceAllStringFunc(row.(string), func(id string) string {
						if known[id] {
							return id
						}
						return "<generated>"
					})
				}
				sort.Strings(masked)
				sorted := make([]any, len(masked))
				for k, row := range masked {
					sorted[k] = row
				}
				probes[j] = sorted
			case probeNow:
				if len(rows) == 1 {
					if now, ok := rows[0].(string); ok && now != "" {
						out[i] = replaceText(out[i], now, transactionNow)
					}
				}
			}
		}
	}
	return out
}

// ---------------------------------------------------------------------------
// Cases
// ---------------------------------------------------------------------------

func outingRepoOracleCases() ([]socialCase, oracleSpec) {
	w := newOutingWorld()
	var cases []socialCase
	add := func(name, wantEnd string, steps ...oracleCall) {
		cases = append(cases, socialCase{oracleCase{Name: name, Setup: append([]string{}, w.sql...),
			Steps: steps}, wantEnd})
	}
	probes := append(append([]string{probeLocks, probeWrites, probeOutingRowLocks}, outingsDump,
		outingStopsDump, outingArrivalDmp, outingInvitesDump, outingMembersDump), probeNow)
	args := func(pairs ...any) map[string]any {
		out := map[string]any{}
		for i := 0; i < len(pairs); i += 2 {
			out[pairs[i].(string)] = pairs[i+1]
		}
		return out
	}
	step := func(call string, pairs ...any) oracleCall {
		return oracleCall{Call: call, Args: args(pairs...), Before: append([]string{}, writesBaseline...),
			Probes: append([]string{}, probes...)}
	}
	tweak := func(sql string, s oracleCall) oracleCall {
		s.Before = append([]string{sql}, s.Before...)
		return s
	}
	const now = outingNow
	later := func(n int) string { return fmt.Sprintf("2030-10-01T06:0%d:00.654321Z", n) }
	const expires = "2030-10-08T05:00:00.123456Z"

	line := func(minute int, label string, placeName, placeID any) map[string]any {
		return map[string]any{"minute_of_day": minute, "label": label, "place_name": placeName,
			"place_id": placeID}
	}
	const caPhe = "Cà phê sáng (dữ liệu mẫu)"
	const quanA = "Quán A (dữ liệu mẫu)"
	const cho = "Chợ (dữ liệu mẫu)"
	const bien = "Biển (dữ liệu mẫu)"
	const moi = "Mới (dữ liệu mẫu)"

	plan := func(id string, minute int, label string, extra ...any) map[string]any {
		stop := map[string]any{"id": id, "minute_of_day": minute, "label": label, "place_name": nil,
			"place_id": nil, "day": nil, "duration_minutes": nil, "time_locked": true,
			"meeting_point": nil}
		for i := 0; i < len(extra); i += 2 {
			stop[extra[i].(string)] = extra[i+1]
		}
		return stop
	}

	// --- reading ------------------------------------------------------------
	add("list_outings: a group's trips, another group's, a pair's, and none", "",
		step("list_outings", "context_id", w.group),
		step("list_outings", "context_id", w.other),
		step("list_outings", "context_id", w.pairCtx),
		step("list_outings", "context_id", w.missingContext))
	add("get_outing: with stops, without, and missing", "",
		step("get_outing", "outing_id", w.oMulti),
		step("get_outing", "outing_id", w.oEmpty),
		step("get_outing", "outing_id", w.oPlan),
		step("get_outing", "outing_id", w.missingOuting))
	add("get_outing_stop: a plain stop, one with a meeting point, and none", "",
		step("get_outing_stop", "stop_id", w.s1),
		step("get_outing_stop", "stop_id", w.t3),
		step("get_outing_stop", "stop_id", w.missingStop))
	add("list_outing_checkins: a tie on created_at, and a trip with none", "",
		step("list_outing_checkins", "outing_id", w.oMulti),
		step("list_outing_checkins", "outing_id", w.oEmpty))

	// --- arrivals -----------------------------------------------------------
	add("create_stop_checkin: a first arrival, then the list", "",
		step("create_stop_checkin", "stop_id", w.s1, "person_id", w.an, "now", now),
		step("list_outing_checkins", "outing_id", w.oMulti),
		step("get_outing", "outing_id", w.oMulti))
	add("create_stop_checkin: the same person twice", "ALREADY_CHECKED_IN",
		step("create_stop_checkin", "stop_id", w.s1, "person_id", w.binh, "now", now))
	add("create_stop_checkin: a stop nobody has", "STOP_NOT_FOUND",
		step("create_stop_checkin", "stop_id", w.missingStop, "person_id", w.an, "now", now))
	add("create_stop_checkin: a stop deleted between the read and the write", "STOP_NOT_FOUND",
		step("create_stop_checkin", "stop_id", w.s4, "person_id", w.an, "now", now),
		tweak(`DELETE FROM outing_stops WHERE id = '`+w.s4+`'`,
			step("create_stop_checkin", "stop_id", w.s4, "person_id", w.binh, "now", later(1))))

	// --- the version 1 timeline ---------------------------------------------
	add("replace_outing_stops: a permutation that keeps every stop and moves two places", "",
		step("replace_outing_stops", "outing_id", w.oMulti, "expected_revision", 4, "stops", []any{
			line(700, bien, nil, nil),
			line(480, caPhe, quanA, "p-a"),
			line(600, cho, nil, "p-c"),
			line(480, caPhe, quanA, "p-b"),
		}),
		step("list_outing_checkins", "outing_id", w.oMulti))
	add("replace_outing_stops: one kept, one dropped, two invented", "",
		step("replace_outing_stops", "outing_id", w.oMulti, "expected_revision", 4, "stops", []any{
			line(600, cho, nil, "p-c"),
			line(900, moi, nil, nil),
			line(1000, moi, "Quán mới (dữ liệu mẫu)", nil),
		}),
		step("list_outing_checkins", "outing_id", w.oMulti))
	add("replace_outing_stops: one stop invented on an empty trip", "",
		step("replace_outing_stops", "outing_id", w.oEmpty, "expected_revision", 0, "stops", []any{
			line(480, moi, nil, nil),
		}))
	add("replace_outing_stops: every stop dropped", "",
		step("replace_outing_stops", "outing_id", w.oMulti, "expected_revision", 4, "stops", []any{}))
	add("replace_outing_stops: a one-day trip writes the day on a new stop", "",
		step("replace_outing_stops", "outing_id", w.oDay, "expected_revision", nil, "stops", []any{
			line(480, moi, nil, nil), line(540, moi, nil, "p-c"),
		}),
		step("replace_outing_stops", "outing_id", w.oDay, "expected_revision", 2, "stops", []any{
			line(540, moi, nil, "p-c"), line(480, moi, nil, nil),
		}))
	add("replace_outing_stops: a stale revision", "TIMELINE_REVISION_CONFLICT",
		step("replace_outing_stops", "outing_id", w.oMulti, "expected_revision", 9, "stops", []any{}))
	add("replace_outing_stops: a trip already on the new itinerary", "ITINERARY_UPGRADE_REQUIRED",
		step("replace_outing_stops", "outing_id", w.oPlan, "expected_revision", 7, "stops", []any{}))
	add("replace_outing_stops: no such trip", "OUTING_NOT_FOUND",
		step("replace_outing_stops", "outing_id", w.missingOuting, "expected_revision", nil, "stops", []any{}))

	// --- the version 2 itinerary ---------------------------------------------
	dayOne := outingDayJSON("2030-10-01", "motorbike", "08:00", nil, nil, false)
	add("replace_outing_itinerary: a permutation of the stored plan, one dropped, one invented", "",
		step("replace_outing_itinerary", "outing_id", w.oPlan, "expected_revision", 7,
			"itinerary_days", []any{
				outingDayJSON("2030-10-01", "car", "07:30", "tmp-moi", w.t1, true),
				outingDayJSON("2030-10-02", "walk", "09:00", nil, nil, false),
			},
			"stops", []any{
				plan("tmp-moi", 400, moi, "day", "2030-10-01", "duration_minutes", 45),
				plan(w.t1, 481, "Sáng (dữ liệu mẫu)", "day", "2030-10-01", "duration_minutes", 30,
					"time_locked", false),
				plan(w.t3, 600, "Chiều (dữ liệu mẫu)", "day", "2030-10-02", "meeting_point",
					map[string]any{"lat": 10.7702, "lng": 106.7, "label": "Cổng chính (dữ liệu mẫu)"}),
			}),
		step("get_outing", "outing_id", w.oPlan))
	add("replace_outing_itinerary: the same plan and the same days write only the revision", "",
		step("replace_outing_itinerary", "outing_id", w.oPlan, "expected_revision", 7,
			"itinerary_days", []any{dayOne},
			"stops", []any{
				plan(w.t1, 480, "Sáng (dữ liệu mẫu)", "day", "2030-10-01", "duration_minutes", 30,
					"time_locked", false),
				plan(w.t2, 540, "Trưa (dữ liệu mẫu)", "day", "2030-10-01", "place_id", "p-a"),
				plan(w.t3, 600, "Chiều (dữ liệu mẫu)", "day", "2030-10-02", "meeting_point",
					map[string]any{"lat": 10.7702, "lng": 106.7, "label": "Cổng chính (dữ liệu mẫu)"}),
			}))
	add("replace_outing_itinerary: a version 1 trip upgraded, every old stop dropped", "",
		step("replace_outing_itinerary", "outing_id", w.oMulti, "expected_revision", 4,
			"itinerary_days", []any{outingDayJSON("2030-10-02", "walk", "10:00", "tmp-a", "tmp-b", false)},
			"stops", []any{
				plan("tmp-a", 600, moi, "day", "2030-10-02"),
				plan("tmp-b", 660, moi, "day", "2030-10-02"),
			}),
		step("list_outing_checkins", "outing_id", w.oMulti))
	add("replace_outing_itinerary: a version 1 trip upgraded with no days named", "",
		step("replace_outing_itinerary", "outing_id", w.oMulti, "expected_revision", 4,
			"itinerary_days", []any{}, "stops", []any{plan("tmp-mot", 480, moi)}))
	add("replace_outing_itinerary: nothing left on the plan", "",
		step("replace_outing_itinerary", "outing_id", w.oPlan, "expected_revision", 7,
			"itinerary_days", []any{}, "stops", []any{}))
	add("replace_outing_itinerary: a stop of another trip", "STOP_NOT_FOUND",
		step("replace_outing_itinerary", "outing_id", w.oPlan, "expected_revision", 7,
			"itinerary_days", []any{}, "stops", []any{plan(w.s1, 480, caPhe)}))
	add("replace_outing_itinerary: a stale revision", "TIMELINE_REVISION_CONFLICT",
		step("replace_outing_itinerary", "outing_id", w.oPlan, "expected_revision", 1,
			"itinerary_days", []any{}, "stops", []any{}))
	add("replace_outing_itinerary: no such trip", "OUTING_NOT_FOUND",
		step("replace_outing_itinerary", "outing_id", w.missingOuting, "expected_revision", 0,
			"itinerary_days", []any{}, "stops", []any{}))

	// --- invitations -----------------------------------------------------------
	add("create_outing_invite: a link, then a named one, then a second for the same person",
		"IntegrityError",
		step("create_outing_invite", "outing_id", w.oMulti, "source", "link", "invited_person_id", nil,
			"invited_by_id", w.an, "token", "moi-moi-mau", "expires_at", expires, "now", now),
		step("create_outing_invite", "outing_id", w.oMulti, "source", "friend", "invited_person_id", w.ngoai,
			"invited_by_id", w.an, "token", "moi-ngoai-mau", "expires_at", expires, "now", now),
		step("get_outing_invite_by_digest", "token", "moi-moi-mau"),
		step("create_outing_invite", "outing_id", w.oMulti, "source", "group", "invited_person_id", w.binh,
			"invited_by_id", w.chi, "token", "moi-binh-lan-hai-mau", "expires_at", expires, "now", now))
	add("find_outing_invite_for_person: named, revoked-but-still-there, and nobody", "",
		step("find_outing_invite_for_person", "outing_id", w.oMulti, "person_id", w.binh),
		step("find_outing_invite_for_person", "outing_id", w.oMulti, "person_id", w.chi),
		step("find_outing_invite_for_person", "outing_id", w.oMulti, "person_id", w.an))
	add("get_outing_invite and get_outing_invite_by_digest: found and not", "",
		step("get_outing_invite", "invite_id", w.invNamed),
		step("get_outing_invite", "invite_id", w.missingInvite),
		step("get_outing_invite_by_digest", "token", w.tokLink),
		step("get_outing_invite_by_digest", "token", w.tokUnused))
	add("accept_outing_invite: a live link, then the digest that reached it", "",
		step("accept_outing_invite", "invite_id", w.invLink, "accepted_by_id", w.ngoai, "now", now),
		step("get_outing_invite_by_digest", "token", w.tokLink))
	add("accept_outing_invite: one already spent", "OUTING_INVITE_ALREADY_ACCEPTED",
		step("accept_outing_invite", "invite_id", w.invAccepted, "accepted_by_id", w.ngoai, "now", now))
	add("accept_outing_invite: one revoked", "OUTING_INVITE_NOT_REDEEMABLE",
		step("accept_outing_invite", "invite_id", w.invRevoked, "accepted_by_id", w.ngoai, "now", now))
	add("accept_outing_invite: one whose deadline has passed", "OUTING_INVITE_NOT_REDEEMABLE",
		step("accept_outing_invite", "invite_id", w.invExpired, "accepted_by_id", w.ngoai, "now", now))
	add("accept_outing_invite: expiring exactly now", "OUTING_INVITE_NOT_REDEEMABLE",
		tweak(`UPDATE outing_invites SET expires_at = '`+now+`' WHERE id = '`+w.invLink+`'`,
			step("accept_outing_invite", "invite_id", w.invLink, "accepted_by_id", w.ngoai, "now", now)))
	add("accept_outing_invite: no such invitation", "OUTING_INVITE_NOT_FOUND",
		step("accept_outing_invite", "invite_id", w.missingInvite, "accepted_by_id", w.ngoai, "now", now))
	add("revoke_outing_invite: a live link, then the same row again", "",
		step("revoke_outing_invite", "invite_id", w.invLink, "now", now),
		step("revoke_outing_invite", "invite_id", w.invLink, "now", later(2)))
	add("revoke_outing_invite: one already spent", "OUTING_INVITE_ALREADY_ACCEPTED",
		step("revoke_outing_invite", "invite_id", w.invAccepted, "now", now))
	add("revoke_outing_invite: no such invitation", "OUTING_INVITE_NOT_FOUND",
		step("revoke_outing_invite", "invite_id", w.missingInvite, "now", now))
	add("rotate_outing_invite_digest: a new secret, then the same one again", "",
		step("rotate_outing_invite_digest", "invite_id", w.invNamed, "token", "moi-binh-lan-ba-mau",
			"expires_at", expires, "now", now),
		step("get_outing_invite_by_digest", "token", w.tokNamed),
		step("get_outing_invite_by_digest", "token", "moi-binh-lan-ba-mau"),
		step("rotate_outing_invite_digest", "invite_id", w.invNamed, "token", "moi-binh-lan-ba-mau",
			"expires_at", expires, "now", later(3)))
	add("rotate_outing_invite_digest: a link names nobody", "OUTING_INVITE_NOT_NAMED",
		step("rotate_outing_invite_digest", "invite_id", w.invLink, "token", "khong-duoc-mau",
			"expires_at", expires, "now", now))
	add("rotate_outing_invite_digest: a named row already revoked", "OUTING_INVITE_NOT_REDEEMABLE",
		step("rotate_outing_invite_digest", "invite_id", w.invNamedRevoked, "token", "khong-duoc-mau",
			"expires_at", expires, "now", now))
	add("rotate_outing_invite_digest: no such invitation", "OUTING_INVITE_NOT_FOUND",
		step("rotate_outing_invite_digest", "invite_id", w.missingInvite, "token", "khong-duoc-mau",
			"expires_at", expires, "now", now))

	// --- the membership a link creates -----------------------------------------
	add("ensure_invited_membership: a newcomer, then somebody already in the roster", "",
		step("ensure_invited_membership", "context_id", w.group, "person_id", w.ngoai,
			"invited_by_id", w.an, "origin", "link", "now", now),
		step("ensure_invited_membership", "context_id", w.group, "person_id", w.binh,
			"invited_by_id", w.an, "origin", "link", "now", now),
		step("ensure_invited_membership", "context_id", w.group, "person_id", w.khach,
			"invited_by_id", w.an, "origin", "named", "now", now),
		step("ensure_invited_membership", "context_id", w.group, "person_id", w.dung,
			"invited_by_id", w.chi, "origin", "named", "now", now))

	// --- routes ---------------------------------------------------------------
	route := func(call, actor string, pairs ...any) oracleCall {
		return step(call, append([]any{"actor_id", actor, "now", now}, pairs...)...)
	}
	add("route.create_outing: a member, then somebody outside the group", "403:permission_denied",
		route("route.create_outing", w.an, "context_id", w.group, "body", map[string]any{
			"title": "  Chuyến mới (dữ liệu mẫu)  ", "starts_on": "2030-12-01", "ends_on": "2030-12-03",
			"headcount": 4, "budget_per_person_vnd": 750000}),
		route("route.create_outing", w.ngoai, "context_id", w.group, "body", map[string]any{
			"title": "Không được (dữ liệu mẫu)", "starts_on": "2030-12-01", "ends_on": "2030-12-01",
			"headcount": 2, "budget_per_person_vnd": 0}))
	add("route.list_context_outings: a member, and an invited link holder", "403:permission_denied",
		route("route.list_context_outings", w.an, "context_id", w.group),
		route("route.list_context_outings", w.khach, "context_id", w.group))
	add("route.replace_outing_timeline: a save that keeps the stop somebody has arrived at", "",
		route("route.replace_outing_timeline", w.an, "outing_id", w.oMulti, "body", map[string]any{
			"expected_revision": 4, "stops": []any{
				map[string]any{"at": "10:00", "label": cho, "place_name": nil, "place_id": "p-c"},
				map[string]any{"at": "08:00", "label": caPhe, "place_name": quanA, "place_id": nil},
			}}),
		route("route.list_outing_checkins", w.an, "outing_id", w.oMulti))
	add("route.replace_outing_timeline: a catalogue key nobody has", "422:stop_place_unknown",
		route("route.replace_outing_timeline", w.an, "outing_id", w.oMulti, "body", map[string]any{
			"expected_revision": 4, "stops": []any{
				map[string]any{"at": "08:00", "label": caPhe, "place_name": nil, "place_id": "p-khong-co"},
			}}))
	add("route.replace_outing_timeline: a trip nobody has", "404:outing_not_found",
		route("route.replace_outing_timeline", w.an, "outing_id", w.missingOuting, "body", map[string]any{
			"expected_revision": nil, "stops": []any{}}))
	add("route.replace_outing_timeline: a stale revision", "409:timeline_conflict",
		route("route.replace_outing_timeline", w.an, "outing_id", w.oMulti, "body", map[string]any{
			"expected_revision": 1, "stops": []any{}}))
	add("route.replace_outing_timeline: a trip of a group the actor is not in", "403:permission_denied",
		route("route.replace_outing_timeline", w.an, "outing_id", w.oOther, "body", map[string]any{
			"expected_revision": 0, "stops": []any{}}))

	itineraryBody := func(revision int, stops []any, days []any, extra ...any) map[string]any {
		body := map[string]any{"expected_revision": revision, "stops": stops, "days": days}
		for i := 0; i < len(extra); i += 2 {
			body[extra[i].(string)] = extra[i+1]
		}
		return body
	}
	dayBody := func(day, mode, startAt string, start, end any) map[string]any {
		return map[string]any{"day": day, "transport_mode": mode, "start_at": startAt,
			"start_stop_id": start, "end_stop_id": end, "return_to_start": false}
	}
	stopBody := func(id, at, label string, extra ...any) map[string]any {
		stop := map[string]any{"id": id, "at": at, "label": label, "place_name": nil, "place_id": nil,
			"day": nil, "duration_minutes": nil, "time_locked": true, "meeting_point": nil}
		for i := 0; i < len(extra); i += 2 {
			stop[extra[i].(string)] = extra[i+1]
		}
		return stop
	}
	add("route.preview_outing_itinerary: a draft whose places resolve, then a day outside the trip",
		"422:itinerary_day_invalid",
		route("route.preview_outing_itinerary", w.an, "outing_id", w.oPlan, "body",
			itineraryBody(7, []any{
				stopBody(w.t2, "09:00", "Trưa (dữ liệu mẫu)", "day", "2030-10-01", "place_id", "p-a"),
				stopBody(w.t3, "10:00", "Chiều (dữ liệu mẫu)", "day", "2030-10-02"),
			}, []any{dayBody("2030-10-01", "motorbike", "08:00", w.t2, w.t2),
				dayBody("2030-10-02", "walk", "09:00", nil, nil)}, "day", "2030-10-01",
				"include_suggestion", false)),
		route("route.preview_outing_itinerary", w.an, "outing_id", w.oPlan, "body",
			itineraryBody(7, []any{}, []any{}, "day", "2030-11-11", "include_suggestion", false)))
	add("route.preview_outing_itinerary: a day outside the trip", "422:itinerary_day_invalid",
		route("route.preview_outing_itinerary", w.an, "outing_id", w.oPlan, "body",
			itineraryBody(7, []any{}, []any{dayBody("2030-11-01", "walk", "08:00", nil, nil)},
				"day", "2030-10-01", "include_suggestion", false)))
	add("route.preview_outing_itinerary: an anchor that is not on its day", "422:itinerary_anchor_invalid",
		route("route.preview_outing_itinerary", w.an, "outing_id", w.oPlan, "body",
			itineraryBody(7, []any{stopBody(w.t1, "08:00", "Sáng (dữ liệu mẫu)", "day", "2030-10-01")},
				[]any{dayBody("2030-10-01", "walk", "08:00", w.t3, nil)},
				"day", "2030-10-01", "include_suggestion", false)))
	add("route.replace_outing_itinerary: a save, then a catalogue key nobody has",
		"422:stop_place_unknown",
		route("route.replace_outing_itinerary", w.an, "outing_id", w.oPlan, "body",
			itineraryBody(7, []any{
				stopBody("tmp-1", "07:00", moi, "day", "2030-10-01", "duration_minutes", 20),
				stopBody(w.t1, "08:00", "Sáng (dữ liệu mẫu)", "day", "2030-10-01", "time_locked", false),
				stopBody(w.t3, "10:00", "Chiều (dữ liệu mẫu)", "day", "2030-10-02", "meeting_point",
					map[string]any{"lat": 10.5, "lng": 106.5, "label": "Cổng sau (dữ liệu mẫu)"}),
			}, []any{dayBody("2030-10-01", "car", "06:30", "tmp-1", w.t1),
				dayBody("2030-10-02", "walk", "09:00", nil, nil)})),
		route("route.replace_outing_itinerary", w.an, "outing_id", w.oPlan, "body",
			itineraryBody(8, []any{stopBody("tmp-2", "07:00", moi, "place_id", "p-khong-co")}, []any{})))
	add("route.replace_outing_itinerary: a stop of another trip", "422:stop_not_found",
		route("route.replace_outing_itinerary", w.an, "outing_id", w.oPlan, "body",
			itineraryBody(7, []any{stopBody(w.s1, "08:00", caPhe)}, []any{})))
	add("route.authorize_outing_itinerary: the replay branch, allowed and refused",
		"404:outing_not_found",
		route("route.authorize_outing_itinerary", w.an, "outing_id", w.oPlan),
		route("route.authorize_outing_itinerary", w.an, "outing_id", w.missingOuting))
	// One savepoint per case: SQLAlchemy numbers them per session, so a second
	// arrival in the same case would be sa_savepoint_2 on one side only.
	add("route.check_in_to_stop: an arrival, and the name it is shown under", "",
		route("route.check_in_to_stop", w.an, "stop_id", w.s1))
	add("route.check_in_to_stop: a second press from the same person", "409:already_checked_in",
		route("route.check_in_to_stop", w.binh, "stop_id", w.s1))
	add("route.check_in_to_stop: a stop nobody has", "404:stop_not_found",
		route("route.check_in_to_stop", w.an, "stop_id", w.missingStop))
	add("route.list_outing_checkins: every arrival with its name, then a stranger",
		"403:permission_denied",
		route("route.list_outing_checkins", w.an, "outing_id", w.oMulti),
		route("route.list_outing_checkins", w.ngoai, "outing_id", w.oMulti))
	add("route.create_outing_invite: a link, a friend, a group member already invited",
		"409:invite_already_exists",
		route("route.create_outing_invite", w.an, "outing_id", w.oMulti, "token", "moi-tu-route-mau",
			"body", map[string]any{"source": "link", "person_id": nil}),
		route("route.create_outing_invite", w.an, "outing_id", w.oMulti, "token", "moi-ban-mau",
			"body", map[string]any{"source": "friend", "person_id": w.ngoai}),
		route("route.create_outing_invite", w.an, "outing_id", w.oMulti, "token", "moi-lai-mau",
			"body", map[string]any{"source": "group", "person_id": w.binh}))
	add("route.create_outing_invite: a group invitation for somebody outside the roster",
		"422:participant_not_in_context",
		route("route.create_outing_invite", w.an, "outing_id", w.oMulti, "token", "moi-nguoi-la-mau",
			"body", map[string]any{"source": "group", "person_id": w.ngoai}))
	add("route.create_outing_invite: a person nobody registered", "409:person_not_registered",
		route("route.create_outing_invite", w.an, "outing_id", w.oMulti, "token", "moi-ma-mau",
			"body", map[string]any{"source": "friend", "person_id": w.missingPerson}))
	add("route.create_outing_invite: the door is shut on a pair", "409:not_a_group",
		route("route.create_outing_invite", w.an, "outing_id", w.oPair, "token", "moi-hai-nguoi-mau",
			"body", map[string]any{"source": "link", "person_id": nil}))
	add("route.revoke_outing_invite: a live link, then one already spent",
		"409:invite_already_accepted",
		route("route.revoke_outing_invite", w.an, "outing_id", w.oMulti, "invite_id", w.invLink),
		route("route.revoke_outing_invite", w.an, "outing_id", w.oMulti, "invite_id", w.invAccepted))
	add("route.revoke_outing_invite: an invitation of another trip", "404:invite_not_found",
		route("route.revoke_outing_invite", w.an, "outing_id", w.oPlan, "invite_id", w.invLink))
	add("route.rotate_outing_invite: a named row, then a link", "409:invite_not_named",
		route("route.rotate_outing_invite", w.an, "outing_id", w.oMulti, "invite_id", w.invNamed,
			"token", "moi-binh-xoay-mau"),
		route("route.rotate_outing_invite", w.an, "outing_id", w.oMulti, "invite_id", w.invLink,
			"token", "khong-duoc-mau"))
	add("route.rotate_outing_invite: a named row already revoked", "404:invite_not_found",
		route("route.rotate_outing_invite", w.an, "outing_id", w.oMulti, "invite_id", w.invNamedRevoked,
			"token", "khong-duoc-mau"))
	add("route.accept_outing_invite: a link redeemed, then the same token again",
		"409:invite_already_accepted",
		route("route.accept_outing_invite", w.ngoai, "token", w.tokLink),
		route("route.accept_outing_invite", w.ngoai, "token", w.tokLink))
	add("route.accept_outing_invite: a named secret is not this door's", "404:invite_not_found",
		route("route.accept_outing_invite", w.ngoai, "token", w.tokNamed))
	add("route.accept_outing_invite: a link somebody revoked", "404:invite_not_found",
		route("route.accept_outing_invite", w.ngoai, "token", w.tokRevoked))
	add("route.accept_outing_invite: a link whose deadline has passed", "404:invite_not_found",
		route("route.accept_outing_invite", w.ngoai, "token", w.tokExpired))
	add("route.accept_outing_invite: a word nobody ever issued", "404:invite_not_found",
		route("route.accept_outing_invite", w.ngoai, "token", w.tokUnused))
	add("route.accept_outing_invite: a member of the group redeeming a link", "",
		route("route.accept_outing_invite", w.binh, "token", w.tokLink))

	spec := oracleSpec{Clock: []string{}, Cases: make([]oracleCase, 0, len(cases))}
	for _, c := range cases {
		spec.Cases = append(spec.Cases, c.oracleCase)
	}
	return cases, spec
}

// outingMethods must each answer normally in at least one case.
var outingMethods = []string{
	"get_outing", "list_outings", "get_outing_stop", "list_outing_checkins", "create_stop_checkin",
	"replace_outing_stops", "replace_outing_itinerary", "create_outing_invite",
	"find_outing_invite_for_person", "get_outing_invite", "get_outing_invite_by_digest",
	"accept_outing_invite", "revoke_outing_invite", "rotate_outing_invite_digest",
	"ensure_invited_membership",
	"route.create_outing", "route.list_context_outings", "route.replace_outing_timeline",
	"route.preview_outing_itinerary", "route.replace_outing_itinerary",
	"route.authorize_outing_itinerary", "route.check_in_to_stop", "route.list_outing_checkins",
	"route.create_outing_invite", "route.revoke_outing_invite", "route.rotate_outing_invite",
	"route.accept_outing_invite",
}

// outingBranches are the write branches and locks the corpus must reach in
// Python, each named by the call and a statement only that branch issues.
var outingBranches = []struct{ call, prefix, contains, absent string }{
	{"create_stop_checkin", "SAVEPOINT", "", ""},
	{"create_stop_checkin", "INSERT INTO outing_stop_checkins", "", ""},
	{"create_stop_checkin", "ROLLBACK TO SAVEPOINT", "", ""},
	{"create_stop_checkin", "UPDATE outings SET timeline_revision", "", ""},
	{"replace_outing_stops", "SELECT outings.id, outings.context_id", "FOR UPDATE", ""},
	{"replace_outing_stops", "DELETE FROM outing_stops", "", ""},
	{"replace_outing_stops", "UPDATE outing_stops SET position=?::INTEGER WHERE", "", ""},
	{"replace_outing_stops", "UPDATE outing_stops SET position=?::INTEGER, place_id=?::VARCHAR", "", ""},
	{"replace_outing_stops", "INSERT INTO outing_stops", "RETURNING outing_stops.time_locked, outing_stops.id", ""},
	{"replace_outing_stops", "INSERT INTO outing_stops", "RETURNING outing_stops.time_locked", "outing_stops.id"},
	{"replace_outing_itinerary", "UPDATE outings SET timeline_revision=?::INTEGER, itinerary_version=?::INTEGER, itinerary_days=?::JSONB", "", ""},
	{"replace_outing_itinerary", "UPDATE outings SET timeline_revision=?::INTEGER, itinerary_version=?::INTEGER WHERE", "", ""},
	{"replace_outing_itinerary", "UPDATE outings SET timeline_revision=?::INTEGER WHERE", "", ""},
	{"replace_outing_itinerary", "UPDATE outing_stops SET position=?::INTEGER, minute_of_day=?::INTEGER", "", ""},
	{"replace_outing_itinerary", "UPDATE outing_stops SET position=?::INTEGER WHERE", "", ""},
	{"replace_outing_itinerary", "INSERT INTO outing_stops", "time_locked", ""},
	{"create_outing_invite", "INSERT INTO outing_invites", "", ""},
	{"accept_outing_invite", "UPDATE outing_invites SET accepted_at=?::TIMESTAMP WITH TIME ZONE, accepted_by_id=?::UUID", "", ""},
	{"revoke_outing_invite", "UPDATE outing_invites SET revoked_at=?::TIMESTAMP WITH TIME ZONE", "", ""},
	{"rotate_outing_invite_digest", "UPDATE outing_invites SET token_digest=?, expires_at=?::TIMESTAMP WITH TIME ZONE", "", ""},
	{"ensure_invited_membership", "INSERT INTO memberships", "", ""},
	{"route.create_outing", "INSERT INTO outings", "", ""},
	{"route.accept_outing_invite", "INSERT INTO memberships", "", ""},
	{"route.replace_outing_timeline", "SELECT places.id", "", ""},
	{"route.preview_outing_itinerary", "SELECT outing_stop_checkins.id", "", ""},
	{"route.create_outing_invite", "SELECT memberships.id, memberships.context_id", "", ""},
}

func TestOutingRepositoryOracle(t *testing.T) {
	image := os.Getenv("CORE_PYTHON_IMAGE")
	if image == "" {
		t.Skip("CORE_PYTHON_IMAGE not set; see the comment at the top of outings_repo_oracle_postgres_test.go")
	}
	scripts, err := filepath.Abs("../../../../scripts")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(scripts, "render_w7_repo_oracle.py")); err != nil {
		t.Fatal(err)
	}
	if _, err := testdb.Pool(t).Exec(bg, `CREATE EXTENSION IF NOT EXISTS pgrowlocks WITH SCHEMA public`); err != nil {
		t.Fatal(err)
	}
	pool, url := migratedOracleSchema(t, image, "outing_repo_oracle_")

	cases, built := outingRepoOracleCases()
	payload, err := json.Marshal(built)
	if err != nil {
		t.Fatal(err)
	}
	var spec oracleSpec
	decoder := json.NewDecoder(bytes.NewReader(payload))
	decoder.UseNumber()
	if err := decoder.Decode(&spec); err != nil {
		t.Fatal(err)
	}
	driver := osexec.Command("docker", "run", "--rm", "-i", "--network", "host",
		"-e", "ORACLE_DATABASE_URL="+url, "-v", scripts+":/oracle:ro",
		"--entrypoint", "python", image, "/oracle/render_w7_repo_oracle.py")
	driver.Stdin = bytes.NewReader(payload)
	var stdout, stderr bytes.Buffer
	driver.Stdout, driver.Stderr = &stdout, &stderr
	if err := driver.Run(); err != nil {
		t.Fatalf("render_w7_repo_oracle.py: %v\n%s", err, tail(stderr.Bytes()))
	}
	if out := os.Getenv("CORE_ORACLE_PYTHON_OUT"); out != "" {
		if err := os.WriteFile(out, stdout.Bytes(), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	var python pythonRun
	if err := json.Unmarshal(stdout.Bytes(), &python); err != nil {
		t.Fatalf("python output: %v", err)
	}
	if len(python.Cases) != len(spec.Cases) {
		t.Fatalf("python answered %d cases of %d", len(python.Cases), len(spec.Cases))
	}

	tally := &repoTally{}
	returned := map[string]int{}
	reached := make([]int, len(outingBranches))
	routeSteps := 0
	for i, c := range spec.Cases {
		tally.cases++
		if python.Cases[i].Name != c.Name {
			t.Fatalf("case %d is %q in python", i, python.Cases[i].Name)
		}
		pySteps := []any{}
		for j, s := range python.Cases[i].Steps {
			call := c.Steps[j].Call
			if strings.HasPrefix(call, "route.") {
				routeSteps++
			}
			statements := []any{}
			for _, entry := range s.Statements {
				for k := 0; k < int(entry[1].(float64)); k++ {
					statement := normalizeSQL(entry[0].(string))
					statements = append(statements, statement)
					for b, branch := range outingBranches {
						if call == branch.call && strings.HasPrefix(statement, branch.prefix) &&
							strings.Contains(statement, branch.contains) &&
							(branch.absent == "" || !strings.Contains(statement, branch.absent)) {
							reached[b]++
						}
					}
				}
			}
			warnings := s.Warnings
			if warnings == nil {
				warnings = []any{}
			}
			if s.Error == nil {
				returned[call]++
			}
			pySteps = append(pySteps, generic(t, map[string]any{"result": s.Result, "error": s.Error,
				"warnings": warnings, "statements": statements, "probes": s.Probes}))
		}

		pyCase := python.Cases[i]
		end := ""
		if len(pyCase.Steps) > 0 {
			if e, ok := pyCase.Steps[len(pyCase.Steps)-1].Error.(map[string]any); ok {
				end, _ = e["type"].(string)
				if code, ok := e["code"].(string); ok {
					end = code
				}
			}
		}
		if len(pyCase.Steps) != len(c.Steps) && end == "" {
			t.Errorf("case %q: python ran %d of %d steps", c.Name, len(pyCase.Steps), len(c.Steps))
		}
		if end != cases[i].wantEnd {
			var last any
			if len(pyCase.Steps) > 0 {
				last = pyCase.Steps[len(pyCase.Steps)-1].Error
			}
			t.Errorf("case %q: python ended in %q, the case is written for %q (%v)", c.Name, end,
				cases[i].wantEnd, last)
		}
		if cases[i].wantEnd != "" && len(pyCase.Steps) != len(c.Steps) {
			t.Errorf("case %q: python refused at step %d of %d", c.Name, len(pyCase.Steps), len(c.Steps))
		}

		t.Run(c.Name, func(t *testing.T) {
			golang := normalizeOutingSteps(runOutingGoCase(t, pool, c), c)
			py := normalizeOutingSteps(pySteps, c)
			before := tally.mismatches
			compareCase(t, tally, c, py, golang)
			if tally.mismatches > before {
				logPeopleDifferences(t, c, py, golang)
			}
		})
	}
	for _, method := range outingMethods {
		if returned[method] == 0 {
			t.Errorf("no case reaches a normal return of %s", method)
		}
	}
	for b, branch := range outingBranches {
		if reached[b] == 0 {
			t.Errorf("no case makes python issue, from %s: %s...%s (without %q)", branch.call, branch.prefix,
				branch.contains, branch.absent)
		}
	}
	t.Logf("outing repo oracle: %d cases, %d steps (%d route steps; %d results, %d refusals), %d statements, "+
		"%d probe rows of which %d table rows, %d generated ids bound, %d branches reached, %d mismatches",
		tally.cases, tally.steps, routeSteps, tally.results, tally.errors, tally.statements, tally.probeRows,
		tally.tableRows, tally.generated, len(outingBranches), tally.mismatches)
}

// ---------------------------------------------------------------------------
// Two requests at once (Go only)
// ---------------------------------------------------------------------------

func TestOutingRowLocksSerialiseRequests(t *testing.T) {
	image := os.Getenv("CORE_PYTHON_IMAGE")
	if image == "" {
		t.Skip("CORE_PYTHON_IMAGE not set; see the comment at the top of outings_repo_oracle_postgres_test.go")
	}
	pool, _ := migratedOracleSchema(t, image, "outing_locks_")
	w := newOutingWorld()
	for _, sql := range w.sql {
		if _, err := pool.Exec(bg, sql); err != nil {
			t.Fatalf("seed: %v\n%s", err, sql)
		}
	}
	now := argInstant(outingNow)
	begin := func(t *testing.T, lockTimeout string) pgx.Tx {
		t.Helper()
		tx, err := pool.Begin(bg)
		if err != nil {
			t.Fatal(err)
		}
		t.Cleanup(func() { _ = tx.Rollback(context.Background()) })
		if lockTimeout != "" {
			if _, err := tx.Exec(bg, "SET LOCAL lock_timeout = '"+lockTimeout+"'"); err != nil {
				t.Fatal(err)
			}
		}
		return tx
	}

	t.Run("an arrival holds the trip against a second arrival and against a save", func(t *testing.T) {
		first := begin(t, "")
		if _, err := (Repository{Q: first}).CreateStopCheckin(bg, w.s1, w.an, now); err != nil {
			t.Fatal(err)
		}
		if _, err := (Repository{Q: begin(t, "150ms")}).CreateStopCheckin(bg, w.s3, w.an, now); !lockNotAvailable(err) {
			t.Fatalf("an arrival at another stop of the same trip did not wait: %v", err)
		}
		if _, err := (Repository{Q: begin(t, "150ms")}).ReplaceOutingStops(bg, w.oMulti, nil, nil); !lockNotAvailable(err) {
			t.Fatalf("saving the plan did not wait on the arrival: %v", err)
		}
		if _, err := (Repository{Q: begin(t, "150ms")}).GetOuting(bg, w.oMulti); err != nil {
			t.Fatalf("a plain read must not wait: %v", err)
		}
	})

	t.Run("two saves of one plan serialise, and the loser sees the new revision", func(t *testing.T) {
		first := begin(t, "")
		revision := int64(4)
		if _, err := (Repository{Q: first}).ReplaceOutingStops(bg, w.oMulti, []TimelineStop{
			{MinuteOfDay: 480, Label: "Một mình (dữ liệu mẫu)"}}, &revision); err != nil {
			t.Fatal(err)
		}
		second := begin(t, "")
		done := make(chan error, 1)
		go func() {
			_, err := (Repository{Q: second}).ReplaceOutingStops(bg, w.oMulti, nil, &revision)
			done <- err
		}()
		select {
		case err := <-done:
			t.Fatalf("the second save did not wait for the first: %v", err)
		case <-time.After(300 * time.Millisecond):
		}
		if err := first.Commit(bg); err != nil {
			t.Fatal(err)
		}
		var conflict *Conflict
		if err := <-done; !errors.As(err, &conflict) || conflict.Code != "TIMELINE_REVISION_CONFLICT" {
			t.Fatalf("the second save, after the first committed: %v", err)
		}
	})

	t.Run("two redemptions of one link end as one acceptance", func(t *testing.T) {
		first := begin(t, "")
		if _, err := (Repository{Q: first}).AcceptOutingInvite(bg, w.invLink, w.ngoai, now); err != nil {
			t.Fatal(err)
		}
		second := begin(t, "")
		done := make(chan error, 1)
		go func() {
			_, err := (Repository{Q: second}).AcceptOutingInvite(bg, w.invLink, w.binh, now)
			done <- err
		}()
		select {
		case err := <-done:
			t.Fatalf("the second redemption did not wait for the first: %v", err)
		case <-time.After(300 * time.Millisecond):
		}
		if err := first.Commit(bg); err != nil {
			t.Fatal(err)
		}
		var conflict *Conflict
		if err := <-done; !errors.As(err, &conflict) || conflict.Code != "OUTING_INVITE_ALREADY_ACCEPTED" {
			t.Fatalf("the second redemption, after the first committed: %v", err)
		}
		var holder string
		if err := pool.QueryRow(bg, `SELECT accepted_by_id::text FROM outing_invites WHERE id = $1::UUID`,
			w.invLink).Scan(&holder); err != nil {
			t.Fatal(err)
		}
		if holder != w.ngoai {
			t.Fatalf("the link was spent by %s", holder)
		}
	})
}
